/* eslint-disable @typescript-eslint/no-explicit-any */
// src/contexts/LanguageContext.tsx
/* eslint-disable react-refresh/only-export-components */
import { createContext, useState, useContext, type ReactNode } from 'react';

// 1. สร้าง Dictionary เก็บคำแปลทั้งหมดในเว็บ
const translations = {
  th: {
    translating: 'กำลังแปล...',

    // Login Modal
    login_tab: 'เข้าสู่ระบบ',
    register_tab: 'สมัครสมาชิก',
    password: 'รหัสผ่าน',
    remember_me: 'จดจำฉันไว้',
    forgot_password: 'ลืมรหัสผ่าน?',
    school_province_placeholder: 'จังหวัดของโรงเรียน',
    teacher_rank_placeholder: 'วิทยฐานะของคุณครู',
    processing: 'กำลังดำเนินการ...',
    login_success: 'เข้าสู่ระบบสำเร็จ!',
    account_suspended: 'บัญชีของคุณถูกระงับการใช้งาน',
    unknown_error: 'เกิดข้อผิดพลาดที่ไม่รู้จัก',
    register_success: 'สมัครสมาชิกสำเร็จ!',

    // Footer
    copyright: 'ลิขสิทธิ์ © 2026 - TReN.org',
    languageLabel: 'ภาษาที่ใช้ :',

    // Navbar 
    home: 'หน้าหลัก',
    events: 'กิจกรรม',
    blogs: 'บล็อกบทความ',
    resources: 'คลังความรู้ EAR',
    showcases: 'ผลงานเด่น',
    about: 'เกี่ยวกับเรา',
    about_us_tab_placeholder: 'เกี่ยวกับ TReN',

    // Password Update Page //
    back_to_home: 'กลับสู่หน้าหลัก',
    update_password_title: 'ตั้งรหัสผ่านใหม่',
    update_password_desc: 'กรุณากำหนดรหัสผ่านใหม่ของคุณเพื่อเข้าสู่ระบบ',
    new_password: 'รหัสผ่านใหม่',
    confirm_new_password: 'ยืนยันรหัสผ่านใหม่',
    confirm_password_placeholder: 'กรอกรหัสผ่านใหม่อีกครั้ง',
    invalid_reset_link: 'ลิงก์รีเซ็ตรหัสผ่านไม่ถูกต้องหรือหมดอายุ',
    password_min_length: 'รหัสผ่านต้องมีความยาวอย่างน้อย 6 ตัวอักษร',
    password_mismatch: 'รหัสผ่านใหม่และการยืนยันรหัสผ่านไม่ตรงกัน',
    password_update_success: 'อัปเดตรหัสผ่านสำเร็จ! คุณสามารถเข้าสู่ระบบด้วยรหัสผ่านใหม่ของคุณได้แล้ว',
    password_update_error: 'เกิดข้อผิดพลาดในการอัปเดตรหัสผ่าน กรุณาลองใหม่อีกครั้ง',
    password_min_length_hint: 'อย่างน้อย 6 ตัวอักษร',
    error_same_password: 'กรุณาเลือกใช้รหัสผ่านใหม่ที่แตกต่างจากรหัสผ่านเก่าของคุณ',
    error_weak_password: 'รหัสผ่านอ่อนแอเกินไป กรุณาเลือกรหัสผ่านที่แข็งแรงกว่านี้',

    // Navbar Dropdown 
    profile: 'โปรไฟล์',
    adminDashboard: 'แดชบอร์ดแอดมิน',
    logout: 'ออกจากระบบ',
    upcoming_events_navbar: 'กิจกรรมที่กำลังจะถึง',
    past_events_navbar: 'กิจกรรมที่ผ่านมา',
    history_about_us: 'ประวัติความเป็นมา',
    timeline_about_us: 'ไทมไลน์ TReN',

    history_of_ear_about_us: 'ประวัติ EAR',
    organization_about_us: 'องค์กรของเรา',
    mission_about_us: 'ภารกิจของเรา',
    what_is_tren_about_us: 'TReN คืออะไร',
    ear_team_about_us: 'ทีม EAR',
    constitution_about_us: 'รัฐธรรมนูญ',
    supporter_about_us: 'องค์กรพันธมิตรและผู้สนับสนุน',

    vision_mission_objectives_about_us: 'วิสัยทัศน์ พันธกิจและเป้าหมายหลัก',
    core_principles_about_us: 'หลักการดำเนินงาน 5 ข้อ',
    tren_journey_about_us:'เส้นทางการเติบโตของ TReN',
    core_role_about_us: 'บทบาทและภารกิจหลักของ TReN',
    governance_about_us: 'กรอบการทำงาน',


    // Profile Page
    profile_title: 'โปรไฟล์ของฉัน',
    edit_profile: 'แก้ไขโปรไฟล์',
    published: 'เผยแพร่',
    in_progress: 'อยู่ในระหว่างดำเนินการ',
    edit: 'แก้ไข',
    no_contents_desc: 'ยังไม่มีเนื้อหาที่สร้างขึ้น',
    no_pending_contents_desc: 'ไม่มีเนื้อหาที่รอดำเนินการในขณะนี้',
    loading_profile: 'กำลังโหลดโปรไฟล์...',

    edit_profile_save: 'บันทึกการเปลี่ยนแปลง',
    edit_profile_saving: 'กำลังบันทึก...',
    edit_profile_cancel: 'ยกเลิก',
    save_success: 'บันทึกสำเร็จ!',
    save_error: 'เกิดข้อผิดพลาดในการบันทึก',
    edit_profile_title: 'แก้ไขโปรไฟล์',
    edit_profile_change_photo: 'เปลี่ยนรูปโปรไฟล์',
    first_name: 'ชื่อ',
    last_name: 'นามสกุล',
    select_province: 'เลือกจังหวัด',
    select_position: 'เลือกตำแหน่ง',
    select_rank: 'เลือกตำแหน่งทางวิชาการ',
    teacher: 'ครู',
    assistant_teacher: 'ผู้ช่วยครู',
    cannot_change_email: 'ไม่สามารถเปลี่ยนอีเมลได้',
    password_label: 'รหัสผ่านใหม่ (เว้นว่างหากไม่ต้องการเปลี่ยน)',
    bio: 'ประวัติส่วนตัว',

    status_rejected: 'ปฏิเสธ',
    delete: 'ลบ',
    view_rejection_reason: 'ดูเหตุผล',
    rejection_reason: 'เหตุผลที่ถูกปฏิเสธ',
    close: 'ปิด',
    deleting: 'กำลังลบ...',
    confirm_delete: 'ยืนยันการลบข้อมูล',
    are_you_sure_you_want_to_delete: 'คุณแน่ใจหรือไม่ที่จะลบ',
    this_action_cannot_be_undone: 'การกระทำนี้ไม่สามารถย้อนกลับได้',

    create_blog: 'สร้างบล็อก',
    create_event: 'สร้างกิจกรรม',
    create_showcase: 'สร้างผลงานเด่น',
    create_news: 'สร้างข่าวสาร',
    delete_success: 'ลบข้อมูลเรียบร้อยแล้ว',

    // Create Event Page
    create_event_title: 'สร้างกิจกรรมใหม่',
    create_event_desc: 'สร้างนัดหมายกิจกรรมเพื่อให้ผู้คนเข้าร่วม',
    creat_event_name: 'ชื่อกิจกรรม',
    event_date: 'วันที่',
    event_time: 'เวลา',
    event_location: 'สถานที่',   
    event_brief_description: 'รายละเอียดกิจกรรมโดยย่อ',
    add_image_cover: 'เพิ่มรูปภาพปกกิจกรรม',
    post_event_details: 'เพิ่มรายละเอียดหลังเสร็จกิจกรรม',
    about_event: 'เกี่ยวกับกิจกรรม',
    conclude_info: 'สรุปข้อมูลกิจกรรมหลังจบงานกิจกรรม',
    resource_link: 'ลิงก์รวมรวบข้อมูล',
    up_to_links: 'อัปโหลดได้สูงสุด 2 ลิงก์',
    event_creating: 'กำลังสร้าง...',
    event_submit_btn: 'สร้างกิจกรรม',
    attach_media: 'แนบสื่อ',
    create_event_success: 'สร้างกิจกรรมสำเร็จ!',
    create_event_error: 'เกิดข้อผิดพลาดในการสร้างกิจกรรม',

    update_event_success: 'อัปเดตกิจกรรมสำเร็จ!',
    update_event_error: 'เกิดข้อผิดพลาดในการอัปเดตกิจกรรม',
    edit_event_title: 'แก้ไขกิจกรรม',
    event_save_changes: 'บันทึกการเปลี่ยนแปลง',

    file_size_exceeded: 'ขนาดไฟล์เกิน 5MB',
    invalid_file_type: 'ประเภทไฟล์ไม่ถูกต้อง (รองรับเฉพาะ .jpg, .jpeg, .png)',
    edit_event_success_pending: 'บันทึกการเปลี่ยนแปลงเรียบร้อยแล้ว! โปรดรอการตรวจสอบจากทีมงาน',
    edit_event_success: 'บันทึกการเปลี่ยนแปลงเรียบร้อยแล้ว!',

    add_link: 'เพิ่มลิงก์',
    no_permission: 'คุณไม่มีสิทธิ์เข้าถึงหน้านี้',

    // Comment Section
    share_comments: 'แชร์ความคิดเห็นของคุณ',
    no_comments_yet: 'ยังไม่มีความคิดเห็น เป็นคนแรกที่คอมเมนต์สิ!',
    leave_a_reply: 'แสดงความคิดเห็น',
    write_a_comment: 'เขียนความคิดเห็นของคุณที่นี่...',
    post_comment: 'โพสต์ความคิดเห็น',
    must_log_in_to_comment: 'คุณต้องเข้าสู่ระบบก่อนจึงจะสามารถคอมเมนต์ได้',
    post: 'โพสต์',
    reply: 'ตอบกลับ',
    comment_delete: 'ลบความคิดเห็น',
    view_replies: 'ดูคำตอบ',
    confirm_delete_comment: 'คุณต้องการลบคอมเมนต์นี้ใช่หรือไม่?',
    are_you_sure_you_want_to_delete_comment: 'การลบจะลบการตอบกลับย่อยทั้งหมดด้วย',
    delete_comment_warning: 'การกระทำนี้ไม่สามารถย้อนกลับได้',

    // Blog Detail Page
    success: 'สำเร็จ',
    error: 'เกิดข้อผิดพลาด',
    ok: 'ตกลง',
    no_permission_blog: 'คุณไม่มีสิทธิ์เข้าถึงเนื้อหานี้',
    link_copied: 'คัดลอกลิงก์แล้ว!',
    preview_warning: 'คุณกำลังดูตัวอย่าง (Preview) | สถานะปัจจุบัน:',
    status_in_progress: 'แบบร่าง (In Progress)',
    share_post: 'แชร์โพสต์นี้',
    no_bio: 'ผู้เขียนยังไม่ได้เพิ่มคำอธิบายตัวเอง (Bio)',
    more_posts: 'ดูเพิ่มเติม',
    related_blogs: 'บล็อกที่เกี่ยวข้อง',
    view_all: 'ดูทั้งหมด',
    by_author: 'โดย',
    read_more: 'อ่านเพิ่มเติม',
    loading_blogs: 'กำลังโหลดบล็อก...',
    blog_not_found: 'ไม่พบบล็อกบทความ',

    // Create Blog Page
    msg_edit_pending: 'ส่งข้อมูลที่แก้ไขเพื่อรอตรวจสอบเรียบร้อยแล้ว!',
    msg_edit_success: 'แก้ไขบล็อกสำเร็จแล้ว!',
    msg_create_success: 'สร้างบล็อกสำเร็จแล้ว!',
    msg_edit_draft: 'อัปเดตแบบร่างสำเร็จ!',
    msg_edit_published: 'บันทึกเรียบร้อย',

    msg_create_pending: 'ส่งบล็อกใหม่เพื่อรอตรวจสอบเรียบร้อยแล้ว!',
    msg_create_error: 'เกิดข้อผิดพลาดในการสร้างบล็อก',
    msg_edit_error: 'เกิดข้อผิดพลาดในการแก้ไขบล็อก',
    msg_create_draft: 'สร้างแบบร่างสำเร็จ!',
    msg_create_published: 'เผยแพร่บล็อกสำเร็จ!',

    loading_blogs_editor: 'กำลังโหลดบล็อก...',
    enter_blog_title: 'กรอกชื่อบล็อกของคุณ...',
    start_writing: 'เริ่มเขียนเนื้อหาของคุณที่นี่...',
    back_to_dashboard: 'กลับไปที่แดชบอร์ด',
    save_changes: 'บันทึกการเปลี่ยนแปลง',
    publish: 'เผยแพร่',
    save_draft: 'บันทึกแบบร่าง',
    click_change_image: 'กดเพื่อเปลี่ยนรูปภาพ',
    add_blog_cover: 'เพิ่มรูปหน้าปกบล็อกที่นี่.',
    press_enterToAddTag: 'กดปุ่ม Enter หรือกดปุ่ม "เพิ่ม" เพื่อสร้างแท็ก',
    category_and_tags: 'หมวดหมู่และแท็ก',
    add_tag: 'เพิ่มแท็ก',
    delete_tag: 'ลบแท็ก',
    add_tags: 'เพิ่มแท็ก...',
    add_more_tags: 'เพิ่มแท็กเพิ่มเติม...',

    as_new_tag: 'เป็นแท็กใหม่: ',
    tag_input_hint: '* ค้นหาแท็กที่เคยใช้ หรือพิมพ์แท็กใหม่แล้วกด Enter เพื่อเพิ่ม',
    link_title: 'ลิงก์แหล่งที่มา, URL สไลด์, หรือ URL YouTube/Vimeo',

    // All Blogs Page
    teacher_blogs: 'บล็อกของคุณครู',
    all_teachers_blogs: 'บล็อกของคุณครู',
    search_explore_blogs: 'ค้นหาและสำรวจบล็อกทั้งหมดได้ที่นี่',
    search_blogs_placeholder: 'ค้นหาโดยชื่อผู้เขียน บล็อก หรือ แท็ก..',
    next: 'ถัดไป',
    no_blogs_found: 'ไม่พบบล็อก',
    no_blogs_found_desc: 'ไม่พบบทความที่ตรงกับการค้นหา หรือในหมวดหมู่นี้',
    all: 'ทั้งหมด',
    no_image: 'ไม่มีรูปภาพ',
    tag_research: 'งานวิจัย',
    tag_tips: 'เคล็ดลับ',
    tag_teaching: 'การสอน',
    tag_innovation: 'นวัตกรรม',
    tag_other: 'อื่นๆ',

    // All Events Page
    all_events: 'กิจกรรมทั้งหมด',
    search_explore_events: 'ค้นหาและสำรวจกิจกรรมทั้งหมดได้ที่นี่',
    search_events_placeholder: 'ค้นหาโดยชื่อกิจกรรมหรือคีย์เวิร์ด..',
    previous: 'ก่อนหน้า',
    no_events_found: 'ไม่พบกิจกรรม',
    no_events_found_desc: 'ไม่พบกิจกรรมที่ตรงกับการค้นหา หรือในหมวดหมู่นี้',
    all_event_date: 'วันที่',
    all_event_time: 'เวลา',
    all_event_place: 'สถานที่',
    all_event_no_brief_description: 'ไม่มีคำอธิบายโดยย่อ',
    
    filter_all: 'ทั้งหมด',
    filter_upcoming: 'กำลังจะมาถึง',
    filter_past: 'ผ่านไปแล้ว',
    filter_done: 'เสร็จสิ้น',

    // All Showcases Page
    showcases_menu: 'ผลงานทั้งหมด',
    all_showcases_title: 'ผลงานทั้งหมด',
    search_explore_showcases: 'ค้นหาและสำรวจผลงานทั้งหมดได้ที่นี่',
    search_showcases_placeholder: 'ค้นหาโดยชื่อผลงาน ผู้สร้าง หรือ คีย์เวิร์ด..',
    no_showcases_found: 'ไม่พบผลงาน',
    no_showcases_found_desc: 'ไม่พบผลงานที่ตรงกับการค้นหา หรือในหมวดหมู่นี้',
    explore_showcases_desc: 'สำรวจและค้นพบผลงานที่สร้างโดยคุณครูเพื่อเป็นแรงบันดาลใจสำหรับผลงานของคุณเอง!',
    tag_article: 'บทความ',
    tag_presentation: 'การนำเสนอ',

    
    // Create Showcase Page
    require_title: 'กรุณากรอกชื่อผลงาน',
    require_login: 'คุณต้องเข้าสู่ระบบก่อนจึงจะสามารถสร้างผลงานได้',
    require_description: 'กรุณากรอกคำอธิบาย',
    create_showcase_success: 'สร้างผลงานสำเร็จ!',
    edit_showcase_pending: 'บันทึกการเปลี่ยนแปลงแล้ว!',
    edit_showcase_success: 'อัปเดตผลงานสำเร็จ!',
    edit_showcase_published: 'บันทึกเรียบร้อย',
    create_showcase_published: 'เผยแพร่ผลงานสำเร็จ!',
    create_showcase_pending: 'ส่งผลงานของคุณเรียบร้อยแล้ว',
    error_saving: 'เกิดข้อผิดพลาดขณะบันทึกผลงาน',
    create_showcase_error: 'เกิดข้อผิดพลาดขณะสร้างผลงาน',
    edit_showcase_error: 'เกิดข้อผิดพลาดขณะแก้ไขผลงาน',
    create_showcase_title: 'สร้างผลงานเด่น',
    edit_showcase_title: 'แก้ไขผลงาน',
    save_showcase_changes: 'บันทึกการเปลี่ยนแปลง',
    create_showcase_desc: 'แบ่งปันผลงานของคุณกับครูท่านอื่น ๆ',
    create_showcase_title_name: 'ชื่อผลงาน',
    create_showcase_author: 'ผู้สร้าง',
    create_showcase_description: 'คำอธิบาย',
    create_showcase_add_image: 'เพิ่มรูปหน้าปก',
    link_to_work: 'ลิงก์ไปยังผลงานของคุณ',
    create_showcase_image_desc: 'คุณสามารถเพิ่มรูปภาพเพื่อแสดงผลงานของคุณ (ไม่จำเป็น)',
    showcase_brief_description: 'คำอธิบายโดยย่อ',
    change_media: 'เปลี่ยนไฟล์สื่อ',
    create_showcase_btn: 'สร้างผลงาน',
    published_date: 'วันที่เผยแพร่',
    visit_work: 'ไปยังหน้าผลงาน',
    create_showcase_author_hint: 'ค้นหาชื่อครูในระบบ หรือพิมพ์ชื่อเองแล้วกด Enter เพื่อเพิ่ม',
    searching: 'กำลังค้นหา...',
    add: 'เพิ่ม',
    no_links_provided: 'ไม่มีลิงก์ที่มาสำหรับผลงานนี้',

    // Admin Dashboard Sidebar
    menu: 'รายการทั้งหมด',
    admin_menu: 'รายการทั้งหมด',
    overview: 'ภาพรวม',
    blog: 'บล็อกบทความ',
    event: 'กิจกรรม',
    showcase: 'ผลงานเด่น',
    resource: 'คลังความรู้',
    reports: 'รายงาน',
    users: 'ผู้ใช้งาน',
    search: 'ค้นหา...',
    status: 'สถานะ',

    // Admin Dashboard Table
    type: 'ประเภท',
    titleSubject: 'ชื่อ/หัวข้อ',
    submittedBy: 'สร้างโดย',
    date: 'ณ วันที่',
    view: 'รายละเอียด',
    action: 'การดำเนินการ',

    // Admin Dashboard Overview
    dashboard: 'ภาพรวมแดชบอร์ด',
    pendingRequests: 'คำขอที่รอดำเนินการ',
    reports_overall: 'รายงาน',
    totalUsers: 'ผู้ใช้งานทั้งหมด',
    recentPendingRequests: 'คำขอที่รอดำเนินการล่าสุด',
    only_admin_can_perform_this_action: 'เฉพาะผู้ดูแลระบบ',
    type_report: 'รายงานทั่วไป',
    type_blog: 'บล็อกบทความ',
    type_event: 'กิจกรรม',
    type_showcase: 'ผลงาน',
    loading: 'กำลังโหลด...',
    showing: 'แสดง',
    to: 'ถึง',
    from: 'จาก',
    list: 'รายการ',
    page: 'หน้า',

    // Admin Blogs
    blog_title: 'บล็อกบทความ',
    no_blogs: 'ไม่พบบล็อกบทความ',
    reject_blog_title: 'ปฏิเสธเนื้อหาบล็อก',
    reject_blog_reason: 'กรุณาระบุเหตุผล:',
    reject_blog_placeholder: 'เช่น เนื้อหาไม่เหมาะสม, ละเมิดลิขสิทธิ์ เป็นต้น...',
    confirm_reject: 'ยืนยัน',
    delete_blog_success: 'ลบบล็อกเรียบร้อยแล้ว',

    // Admin Events
    event_title: 'กิจกรรม',
    no_events: 'ไม่พบกิจกรรม',
    event_actions: 'การดำเนินการ',
    done: 'เสร็จสิ้นกิจกรรม',
    event_status: 'สถานะกิจกรรม',
    publish_state: 'การอนุมัติ',
    status_upcoming: 'กำลังมาถึง',
    status_past: 'ผ่านไปแล้ว',
    status_done: 'เสร็จสิ้น',
    state_pending: 'รอตรวจสอบ',
    state_published: 'เผยแพร่แล้ว',
    state_rejected: 'ไม่อนุมัติ',
    create_date: 'วันที่สร้าง',
    admin_events_confirm_approve: 'คุณแน่ใจหรือไม่ว่าต้องการอนุมัติกิจกรรมนี้?',
    admin_events_confirm_mark_as_done: 'คุณแน่ใจหรือไม่ว่าต้องการเปลี่ยนสถานะกิจกรรมนี้เป็น "เสร็จสิ้น" ?',
    admin_events_mark_as_done_success: 'กิจกรรมถูกทำเครื่องหมายว่าเสร็จสิ้นเรียบร้อยแล้ว',
    admin_events_approve_success: 'อนุมัติกิจกรรมให้เผยแพร่เรียบร้อยแล้ว',
    error_updating_event_occurred: 'เกิดข้อผิดพลาดในการอัปเดตกิจกรรม',
    confirm: 'ตกลง',
    cancel: 'ยกเลิก',
    loading_events: 'กำลังโหลดกิจกรรม...',
    view_event_details: 'ดูรายละเอียดกิจกรรม',
    approve: 'อนุมัติ',
    delete_event_success: 'ลบกิจกรรมเรียบร้อยแล้ว',

    // Admin Showcases
    showcase_title: 'ผลงานเด่น',
    no_showcases: 'ไม่พบผลงานเด่น',
    loading_showcases: 'กำลังโหลดผลงาน...',

    // Admin Reports
    report_title: 'รายงาน',
    no_reports: 'ไม่พบรายงาน',
    loading_reports: 'กำลังโหลดรายงาน...',
    resolved: 'ดำเนินการแล้ว',
    ticket_inquiry: 'สอบถามข้อมูล',
    ticket_bug: 'ปัญหาการใช้งาน',
    ticket_comment: 'รายงานทั่วไป',

    report_desc: 'รายละเอียด',
    reporter: 'ผู้รายงาน',
    report_date: 'วันที่รายงาน',
    admin_note: 'บันทึกการดำเนินการ',
    view_source: 'ไปยังแหล่งที่มา',
    report_category: 'หมวดหมู่การรายงาน',

    confirm_resolved: 'แก้ไขปัญหาเรียบร้อย',
    confirm_resolved_message: 'คุณกำลังอัปเดตสถานะของ',
    resolve_modal_placeholder: 'เช่น ทำการลบบล็อกนี้ออกจากระบบแล้ว, ทำการแบนผู้ใช้งานชั่วคราว...',
    save_report_status: 'บันทึกสถานะ',
    confirm_reject_message: 'คุณกำลังปฏิเสธคำร้องเรียน',
    reject_reason: 'เหตุผลในการปฏิเสธ',
    reject_modal_placeholder: 'เช่น ตรวจสอบแล้วไม่พบการละเมิดกฎ, ข้อมูลไม่เพียงพอ...',
    save_rejection: 'บันทึกการปฏิเสธ',
    delete_report_success: 'ลบรายงานเรียบร้อยแล้ว',
    report_pending: 'รอดำเนินการ',

    // Admin Users
    no_users: 'ไม่พบผู้ใช้งาน',
    id: 'รหัสผู้ใช้',
    profile_pic: 'รูปโปรไฟล์',
    name: 'ชื่อ-นามสกุล',
    role: 'ตำแหน่ง',
    joined_date: 'วันที่เข้าร่วม',
    email: 'อีเมล',
    school: 'โรงเรียน',
    province: 'จังหวัด',
    position: 'ตำแหน่ง',
    academic_rank: 'ตำแหน่งทางวิชาการ',
    total_blogs: 'จำนวนบล็อก',
    total_showcases: 'จำนวนผลงาน',
    ban_user: 'ระงับบัญชีผู้ใช้งาน',
    user: 'ผู้ใช้งาน',
    account_details: 'รายละเอียดผู้ใช้งาน',
    post_count: 'โพสต์',
    showcase_count: 'ผลงาน',

    confirm_ban: 'ยืนยันการระงับบัญชี',
    confirm_ban_message: 'คุณกำลังระงับบัญชีผู้ใช้งาน',
    confirm_unban: 'ยืนยันการปลดระงับบัญชี',
    confirm_unban_message: 'คุณกำลังปลดระงับบัญชีผู้ใช้งาน',
    unban_user: 'ปลดระงับบัญชีผู้ใช้',
    are_you_sure_you_want_to_ban: 'คุณแน่ใจหรือไม่ที่จะระงับบัญชีผู้ใช้งาน',
    user_banned_successfully: 'ระงับบัญชีผู้ใช้งานเรียบร้อยแล้ว',
    user_unbanned_successfully: 'ปลดระงับบัญชีผู้ใช้งานเรียบร้อยแล้ว',
    this_user_login_disabled: 'ผู้ใช้นี้จะไม่สามารถล็อกอินเข้าสู่ระบบได้อีกจนกว่าจะถูกปลดแบน',
    are_you_sure_you_want_to_unban: 'คุณแน่ใจหรือไม่ที่จะปลดระงับบัญชีผู้ใช้งาน',
    banned: 'โดนระงับบัญชี',

    // Confirmation Box Approve/Reject
    confirm_approve: 'ยืนยันการอนุมัติ',
    confirm_approve_message: 'คุณแน่ใจหรือไม่ที่จะอนุมัติ',
    content_will_be_published: 'เนื้อหานี้จะถูกเผยแพร่สู่สาธารณะทันที',
    no_pending_requests: 'ไม่มีคำขอที่รอดำเนินการ',
    reject: 'ปฏิเสธ',

    // Report Modal
    report_modal_title: 'รายงานปัญหา',
    report_modal_desc: 'รายงานเนื้อหาที่ไม่เหมาะสมหรือละเมิดกฎ',
    report_modal_category: 'หัวข้อการรายงาน',
    report_category_inappropriate: 'เนื้อหาไม่เหมาะสม / หยาบคาย',
    report_category_copyright_infringement: 'ละเมิดลิขสิทธิ์',
    report_category_spam_ads: 'สแปม / โฆษณาแอบแฝง',
    report_category_false_information: 'ข้อมูลเท็จ / ทำให้เข้าใจผิด',
    report_category_broken_links: 'ลิงก์เสีย / ใช้งานไม่ได้',
    report_category_other: 'อื่นๆ',
    report_modal_description: 'รายละเอียดเพิ่มเติม',
    report_modal_placeholder: 'โปรดอธิบายปัญหาที่คุณพบ...',
    submit_report: 'ส่งรายงาน',
    report_submitted_success: 'รายงานถูกส่งเรียบร้อยแล้ว!',
    report_submitted_error: 'เกิดข้อผิดพลาดขณะส่งรายงาน',
    report_success: 'สำเร็จ',
    report_error: 'เกิดข้อผิดพลาด',

    // Search Page
    find_info_you_need: 'ค้นหาข้อมูลที่คุณต้องการ',
    No_results_found: 'ไม่พบผลลัพธ์สำหรับ',
    try_different_keywords: 'ลองใช้คำค้นหาที่แตกต่างกัน หรือ ลองดูเนื้อหาทั้งหมด',
    found: 'พบ',
    found_for: 'รายการสำหรับ',

    // Resource Page
    all_resources: 'คลังข้อมูลทั้งหมด',
    resources_desc: 'ค้นหาและสำรวจคลังข้อมูลทั้งหมดได้ที่นี่',
    add_resource: 'เพิ่มข้อมูล',
    search_resources: 'ค้นหาโดยชื่อข้อมูลหรือคีย์เวิร์ด..',
    loading_resources: 'กำลังโหลดคลังข้อมูล...',
    no_resources_found: 'ไม่พบข้อมูล',
    no_resources_found_desc: 'ไม่พบคลังข้อมูลที่ตรงกับการค้นหา หรือในหมวดหมู่นี้',
    view_details: 'ดูรายละเอียด',
    resource_title: 'ชื่อข้อมูล',
    resource_category: 'หมวดหมู่',
    try_different_resource_keywords: 'ลองใช้คำค้นหาที่แตกต่างกัน หรือ ลองดูเนื้อหาทั้งหมด',

    filter_document: 'เอกสาร',
    filter_media: 'รูปภาพและวิดีโอ',
    filter_folder: 'แฟ้มข้อมูล',
    filter_link: 'ลิงก์เว็บไซต์',
    resource_edit_success: 'แก้ไขข้อมูลสำเร็จ',
    resource_create_success: 'สร้างข้อมูลสำเร็จ!',
    resource_delete_success: 'ลบข้อมูลเรียบร้อยแล้ว',

    edit_resource_title: 'แก้ไขข้อมูล',
    create_resource_title: 'สร้างข้อมูล',
    create_resource_desc: 'เพิ่มไฟล์ เอกสาร หรือวิดีโอ เพื่อแบ่งปันให้กันและกัน',
    resource_type: 'ประเภทข้อมูล',
    resource_placeholder: 'เช่น วิดีโอสัมมนาวันที่..., เอกสารประกอบการสอน...',
    resource_url: 'ลิงก์ข้อมูล',
    resource_description: 'คำอธิบายข้อมูล',
    resource_description_placeholder: 'คำอธิบายสั้น ๆ เกี่ยวกับข้อมูลนี้...',
    create_resource_button: 'สร้างข้อมูล',
    edit_resource_button: 'บันทึกการเปลี่ยนแปลง',
    resource_file_size_exceeded: 'ขนาดไฟล์เกิน 10MB',
    resource_invalid_file_type: 'ประเภทไฟล์ไม่ถูกต้อง (รองรับเฉพาะ .jpg, .jpeg, .png, .pdf, .mp4)',

    added_on: 'สร้างเมื่อ: ',
    no_description_provided: 'ไม่มีคำอธิบายสำหรับข้อมูลนี้',
    open_folder: 'เปิดโฟลเดอร์',
    view_media: 'ดูสื่อ',
    open_document: 'เปิดเอกสาร',
    open_link: 'เปิดลิงก์',

    // Home Page
    home_title: 'Teacher-research Network (TReN)',
    home_subtitle: 'เครือข่ายวิจัยในชั้นเรียนเพื่อการเปลี่ยนแปลงที่ยั่งยืน',
    home_description: 'TReN ทำหน้าที่เป็นศูนย์กลางขับเคลื่อนการพัฒนาทักษะการวิจัยเชิงปฏิบัติการแบบสำรวจ (Exploratory Action Research: EAR) ผ่านรูปแบบชุมชนนักปฏิบัติ (Community of Practice: CoP) โดยเชื่อมโยงเครือข่ายครูพี่เลี้ยงและครูทั่วไป ครอบคลุม 8 ภูมิภาคทั่วประเทศ เพื่อยกระดับการจัดการเรียนรู้และเสริมศักยภาพให้ครูสามารถแก้ปัญหาในชั้นเรียนได้ด้วยตนเอง',
    
    our_mission: 'ผลงานตลอด 5 ปีที่ผ่านมา',
    three_hundred_plus: '300+',
    registered_teachers: 'ครูผู้เข้าร่วมโครงการ',
    over_provinces: 'ครอบคลุม 40 \nจังหวัดทั่วประเทศ',
    one_hundred_fifty_plus: '150+',
    research_projects: 'ผลงานวิจัยในชั้นเรียน',
    already_published: 'ได้รับการตีพิมพ์เผยแพร่แล้วกว่า',
    fifty_research_articles: '50 เรื่อง',
    fifty_teachers: '50',
    mentors: 'ครูพี่เลี้ยงวิจัย (Mentor)',
    already_trained: 'ที่ผ่านการพัฒนาศักยภาพและพร้อมทำหน้าที่หนุนเสริมเพื่อนครูในพื้นที่',

    calendar_events: 'ปฏิทินกิจกรรม',
    events_on: 'กิจกรรมในวันที่',
    target_audience: 'กลุ่มเป้าหมาย',
    target_teacher:'ครูทั่วไป',
    target_mentor:'ครูพี่เลี้ยงวิจัย',
    target_everyone:'บุคคลทั่วไป',
    register_join: 'ลงทะเบียนเข้าร่วมกิจกรรม',
    no_events_today: 'ไม่มีการจัดกิจกรรมในวันนี้',
    click_other_dates: 'คลิกเพื่อดูวันที่อื่น ๆ ',

    news: 'ข่าวสาร',
    all_news: 'ข่าวสารทั้งหมด',
    search_explore_news: 'ค้นหาและสำรวจข่าวสารทั้งหมดได้ที่นี่',
    search_news_placeholder: 'ค้นหาโดยชื่อข่าวสารหรือคีย์เวิร์ด..',
    news_announcements: 'ข่าวสารสำคัญ',
    news_earc: 'เรื่องเล่าจากเครือข่ายภูมิภาค',
    news_activity: 'ข่าวสารกิจกรรม',
    no_news: 'ไม่พบข้อมูล',
    view_all_announcements: 'ดูข่าวสารสำคัญทั้งหมด',
    view_all_stories: 'ดูเรื่องเล่าจากเครือข่ายภูมิภาคทั้งหมด',
    view_all_activities: 'ดูข่าวสารกิจกรรมทั้งหมด',
    loading_news: 'กำลังโหลดข่าวสาร...',
    news_category: 'หมวดหมู่ข่าวสาร',
    select_category: 'เลือกหมวดหมู่ข่าวสาร',
    news_category_announcement: 'ข่าวสารสำคัญ',
    news_category_earc: 'เรื่องเล่าจากเครือข่ายภูมิภาค',
    news_category_activity: 'ข่าวสารกิจกรรม',
    enter_news_title: 'กรอกชื่อข่าวสารของคุณ...',
    start_writing_news: 'กรอกรายละเอียดข่าวสารของคุณที่นี่...',
    add_news_cover: 'เพิ่มรูปหน้าปกข่าวสารที่นี่.',
    related_news: 'ข่าวสารที่เกี่ยวข้อง',
    admin_approve_news_success: 'อนุมัติข่าวสารเรียบร้อยแล้ว',
    error_updating_occurred: 'เกิดข้อผิดพลาดในการอนุมัติข่าวสาร',

    // Vision Mission Objectives Page //
    vision_about_tren_title: 'TReN',
    vision_about_tren_subtitle:'เครือข่ายวิจัยครู',
    vision_about_tren_en_title: 'Teacher-research Network',
    vision_about_tren_desc: 'เราคือ TReN (Teacher-Research Network) เครือข่ายวิจัยที่ขับเคลื่อนโดยพลังของครู เพื่อแก้ปัญหาในชั้นเรียนด้วยตัวเอง เรามุ่งมั่นพัฒนาทักษะการวิจัยผ่านกระบวนการ Exploratory Action Research (EAR) สร้างชุมชนนักปฏิบัติ (CoP) หรือ EAR Community (EARC) ทั้ง 4 ภูมิภาคทั่วประเทศ และพัฒนาระบบพี่เลี้ยง (Mentorship) เพื่อสร้างระบบนิเวศการเรียนรู้ที่ยั่งยืน เปลี่ยนการแก้ปัญหาในห้องเรียนให้เป็นการวิจัยที่ตอบโจทย์ และยกระดับผลสัมฤทธิ์ของผู้เรียนอย่างแท้จริง',

    vision_about_vision: 'วิสัยทัศน์',
    vision_about_vision_desc: '"มุ่งเป็นเครือข่ายวิจัยในชั้นเรียนระดับชาติ ที่ขับเคลื่อนให้ครูไทยใช้กระบวนการวิจัย Exploratory Action Research (EAR) พัฒนาการเรียนการสอนได้ด้วยตนเองอย่างยั่งยืน และเติบโตไปด้วยกันอย่างเข้มแข็ง"',

    vision_about_mission: 'พันธกิจ',
    vision_about_mission_subtitle: 'สิ่งที่เรามุ่งมั่นลงมือทำเพื่อขับเคลื่อนการศึกษา',
    vision_about_empowerment: 'พัฒนาทักษะ',
    vision_about_empowerment_en: 'Empowerment',
    vision_about_empowerment_desc: 'ส่งเสริมความรู้ความเข้าใจและทักษะการทำ Exploratory Action Research (EAR) เพื่อให้ครูสามารถนำไปใช้แก้ปัญหาในห้องเรียนได้จริง',
    vision_about_community: 'สร้างเครือข่าย',
    vision_about_community_en: 'Community',
    vision_about_community_desc: 'ขยายชุมชนนักปฏิบัติ (CoP) หรือ EAR Community (EARC) ทั่วประเทศ เพื่อเป็นพื้นที่แลกเปลี่ยนเรียนรู้ร่วมกัน',
    vision_about_sustainability: 'สร้างความยั่งยืน',
    vision_about_sustainability_en: 'Sustainability',
    vision_about_sustainability_desc: 'พัฒนาระบบพี่เลี้ยงและยกระดับศักยภาพของครู เพื่อให้การจัดการเรียนรู้และการทำวิจัยในห้องเรียนขับเคลื่อนได้อย่างต่อเนื่องและยั่งยืน',

    vision_about_core_objectives: 'ภารกิจหลัก',
    vision_about_goal_01: 'เป้าหมายที่ 01',
    vision_about_goal_02: 'เป้าหมายที่ 02',
    vision_about_goal_03: 'เป้าหมายที่ 03',
    vision_about_obj1_en: 'Ecosystem & Support',
    vision_about_obj1_th: 'สร้างระบบนิเวศการเรียนรู้และสนับสนุนครู',
    vision_about_obj1_desc: 'ออกแบบหลักสูตรและสร้างระบบพี่เลี้ยง (Mentorship) เพื่อให้คำปรึกษาเชิงลึก',
    vision_about_obj2_en: 'Network & Community',
    vision_about_obj2_th: 'ขยายเครือข่ายและพื้นที่แลกเปลี่ยนเรียนรู้',
    vision_about_obj2_desc: 'จัดตั้งพื้นที่ CoP (EAR Community - EARC) ทั่วประเทศ และจัดเวทีแลกเปลี่ยนเรียนรู้เพื่อสร้างแรงบันดาลใจ',
    vision_about_obj3_en: 'Sustainability & Impact',
    vision_about_obj3_th: 'ขับเคลื่อนความยั่งยืนและการนำไปใช้',
    vision_about_obj3_desc: 'จัดทำคลังความรู้จาก Best Practices และผลักดันให้เกิดวัฒนธรรมวิจัยในสถานศึกษาอย่างแท้จริง',

    vision_about_vision_headline: 'วิสัยทัศน์',
    vision_about_mission_headline: 'พันธกิจ',
    vision_about_core_objectives_headline: 'ภารกิจหลัก',

    vision_about_tren_desc_1: 'คือ เครือข่ายวิจัยที่ขับเคลื่อนโดยพลังของครู มุ่งมั่นยกระดับศักยภาพครูไทยให้สามารถแก้ปัญหาในชั้นเรียนได้ด้วยตัวเองอย่างตรงจุด ผ่านการทำวิจัยในชั้นเรียนที่เรียกว่า Exploratory Action Research (EAR) หรือการวิจัยเชิงปฏิบัติการเชิงสำรวจ ที่เน้นการนำข้อมูลและหลักฐานจริงจากห้องเรียนมาใช้พัฒนาการเรียนการสอน',
    vision_about_channels_title: 'ช่องทางการเรียนรู้และการเข้าร่วม',
    vision_about_target_general: 'ครูทั่วไป:',
    vision_about_target_general_desc: 'สามารถศึกษาแนวคิด และกระบวนการทำวิจัย EAR ได้ด้วยตนเองผ่านคลังความรู้บนเว็บไซต์นี้',
    vision_about_target_selected: 'ครูที่ได้รับคัดเลือกเข้าร่วมการอบรม:',
    vision_about_target_selected_desc:'จะได้เรียนรู้กระบวนการทำวิจัยอย่างเป็นขั้นตอนแบบเข้มข้น โดยมี "ครูพี่เลี้ยงวิจัย" คอยให้คำแนะนำและดูแลอย่างใกล้ชิดตลอดการทำวิจัย',
    vision_about_tren_desc_2: 'TReN เป็นชุมชนนักปฏิบัติ (CoP) ที่เชื่อมโยงครูผู้สอนใน 4 ภูมิภาคทั่วประเทศเข้าด้วยกัน พร้อมสนับสนุนและเปิดพื้นที่ให้คุณครูได้พัฒนาวิชาชีพ แลกเปลี่ยนประสบการณ์ สร้างมิตรภาพกับเพื่อนครู และจับมือร่วมกันพัฒนาการศึกษาไทยในอนาคต',
    vision_about_vision_subhead: 'Vision',
    vision_about_mission_subhead: 'Mission',
    vision_about_core_objectives_subhead: 'Objectives',


    // Core Principles Page //
    principle_1_title: 'ขับเคลื่อนโดยครู เพื่อครูอย่างแท้จริง',
    principle_1_en: '(Teacher-Led)',
    principle_1_desc: 'บริหารและนำโดยครูโรงเรียนเป็นหลัก ทุกการตัดสินใจเกิดจากความต้องการจริง ปราศจากการสั่งการแบบ Top-down',
    principle_2_title: 'เน้นชุมชนและความร่วมมือ',
    principle_2_en: '(Collaboration)',
    principle_2_desc: 'เป็นชุมชนแห่งการเรียนรู้ (CoP / EARC) ที่สมาชิกพร้อมแบ่งปันและช่วยเหลือเกื้อกูลกันแบบกัลยาณมิตร เพื่อเติบโตไปด้วยกัน',
    principle_3_title: 'มุ่งเน้นห้องเรียนและผลลัพธ์ของผู้เรียน',
    principle_3_en: '(Classroom-Based)',
    principle_3_desc: 'งานวิจัย EAR เริ่มจากปัญหาจริง และปลายทางสร้างการเปลี่ยนแปลงเชิงบวกให้แก่ผู้เรียนโดยไม่เน้นสะสมเอกสารวิชาการ',
    principle_4_title: 'เปิดใจกว้างและเรียนรู้ร่วมกัน',
    principle_4_en: '(Open & Reflective)',
    principle_4_desc: 'สร้าง "พื้นที่ปลอดภัย (Safe Space)" ให้ครูกล้าพูดคุยถึงปัญหา หรือความผิดพลาดในชั้นเรียนเพื่อหาทางออกโดยไม่ถูกตัดสิน พร้อมเปิดรับครูจากทุกสังกัด',
    principle_5_title: 'ส่งต่อความยั่งยืน',
    principle_5_en: '(Sustainable Mentorship)',
    principle_5_desc: 'สร้างระบบส่งต่อความรู้เพื่อพัฒนาครูพี่เลี้ยงรุ่นใหม่ให้สืบสานเครือข่ายอย่างยั่งยืน',

    about_principles_main: 'หลักการดำเนินงาน 5 ข้อ',
    about_principles_count: '5 ข้อ',
    about_principles_subtitle: 'TReN’s 5 Core Principles',
    practice_guideline: 'แนวปฏิบัติ:',

    // Tren Journey Page //
    journey_main_title:'เส้นทางการเติบโต',
    journey_subtitle:'TReN Journey',
    journey_intro_desc: 'จากจุดเริ่มต้นเล็กๆ ในห้องเรียน สู่การขับเคลื่อนเครือข่ายครูนักวิจัยระดับประเทศ เพื่อยกระดับผลสัมฤทธิ์ของผู้เรียนอย่างยั่งยืน (พ.ศ. 2565 - ปัจจุบัน)',
    journey_year_1_title: 'พ.ศ. 2565',
    journey_phase_1:'จุดกำเนิดและความท้าทายในห้องเรียน',
    journey_desc_1_1:'จุดเริ่มต้นของเครือข่าย Teacher-Research Network (TReN) เกิดขึ้นจากความร่วมมือระหว่าง British Council Thailand และ คณะศิลปศาสตร์ มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี (มจธ.) ที่มีเป้าหมายสำคัญในการติดอาวุธให้ครูประจำการสามารถแก้ไขปัญหาในชั้นเรียนได้ด้วยตนเอง',
    journey_desc_1_2:'ในชีวิตการทำงานจริง ครูต้องเผชิญกับความท้าทายหลากหลายรูปแบบ เช่น การใช้วิธีสอนหรือสื่อที่ไม่สอดคล้องกับผู้เรียน ขาดประสิทธิภาพในการจัดการเรียนรู้ หรือภาวะขาดแรงจูงใจของนักเรียน แม้ที่ผ่านมาภาครัฐจะมีมาตรการช่วยเหลือผ่านมาตรการต่างๆ เช่นการส่งศึกษานิเทศก์เข้าเยี่ยมชั้นเรียน นโยบายชุมชนการเรียนรู้ทางวิชาชีพ (PLC) หรือการจัดอบรมเชิงปฏิบัติการ แต่เพราะบริบทและปัญหาของแต่ละห้องเรียนมีความแตกต่างกันอย่างสิ้นเชิง การรอความช่วยเหลือจากภายนอกจึงไม่เพียงพอ',
    journey_key_takeaway:'ทางออกที่ยั่งยืน',
    journey_desc_1_3:'ต้องเริ่มต้นจากการปรับมุมมอง โดยยึดหลักคิดสำคัญว่า ทุกการตัดสินใจของครูต้องอยู่บนพื้นฐานของประจักษ์พยาน ไม่ใช่ความรู้สึกส่วนตัว (evidence-based decision) เพราะบ่อยครั้งที่ครูมักแก้ปัญหาจากอคติหรือประสบการณ์ส่วนตัว ทำให้แก้ปัญหาไม่ตรงจุด การติดอาวุธทางปัญญาให้ครูสามารถวิเคราะห์ปัญหาด้วยตนเองผ่านกระบวนการ Exploratory Action Research (EAR) จึงเป็นคำตอบที่ตอบโจทย์ ทั้งยังสอดคล้องกับเกณฑ์การประเมินและพัฒนาวิชาชีพของ ก.ค.ศ. อย่างแท้จริง',
    journey_year_1_2_title: 'ปีที่ 1 (พ.ศ. 2565)',
    journey_phase_1_2:'จุดประกายและวางรากฐาน',
    journey_desc_2_1:'โครงการเริ่มต้นจากการอบรมครูสอนภาษาอังกฤษจำนวน 21 คน โดยคณะศิลปศาสตร์ มจธ. เป็นผู้จัดกระบวนการอบรม และใช้โมเดลการอบรม Exploratory Action Research (EAR) ซึ่งพัฒนาขึ้นโดย Professor Dr. Richard Smith จาก University of Warwick และ Dr. Paula Rebolledo ซึ่งประสบความสำเร็จมาแล้วในหลายประเทศตั้งแต่ปี 2018',
    journey_desc_2_2:'การอบรมซึ่งทำในช่วงก่อนการเปิดภาคการศึกษาที่ 1 มุ่งเน้นการให้ความรู้ด้านกระบวนการวิจัย จากนั้นตลอด  ภาคการศึกษาที่ 1 ครูได้ลงมือทำวิจัยจริง พร้อมได้รับคำปรึกษาอย่างใกล้ชิดจากผู้เชี่ยวชาญของ British Council และครูพี่เลี้ยงนานาชาติ ซึ่งการมีครูพี่เลี้ยงคอยหนุนเสริมเช่นนี้ถือเป็นหัวใจสำคัญที่ช่วยให้ครูทำวิจัยจนเสร็จสิ้น สอดคล้องกับมุมมองของ ดร.สุวิมล ว่องวาณิช ที่สะท้อนถึงความท้าทายไว้ว่า:',
    journey_quote: 'กระบวนการต่างๆ ที่ใช้ในการทำวิจัย เป็นเรื่องที่ครูไม่คุ้นเคย เข้าใจยาก และต้องอาศัยการฝึกปฏิบัติภายใต้พี่เลี้ยงที่เข้าใจในวิธีการวิจัยอย่างสม่ำเสมอ แต่ในสภาพจริงหลังการฝึกอบรม ครูที่ทำวิจัยกลับขาดพี่เลี้ยงคอยช่วยเหลือ ขาดประสบการณ์และความชำนาญที่แท้จริง ส่งผลให้รายงานวิจัยมีข้อบกพร่อง',
    journey_quote_author: 'ดร.สุวิมล ว่องวาณิช',
    journey_desc_2_3: 'จากผลลัพธ์เมื่อกระบวนการวิจัยสิ้นสุด ครูได้สะท้อนถึงการเปลี่ยนแปลงเชิงบวก ทั้งทัศนคติต่อการทำวิจัยที่ดีขึ้น ความสัมพันธ์ระหว่างครูและนักเรียนที่แน่นแฟ้นยิ่งขึ้น ตลอดจนความสามารถในการแก้ปัญหาห้องเรียนได้อย่างตรงจุดโดยอาศัยหลักฐานเชิงประจักษ์แทนการคาดเดา (Dersingh & Vuong, 2023) ความสำเร็จที่เป็นรูปธรรมเหล่านี้ทำให้ทาง British Council และ มจธ. มั่นใจในคุณค่าของโครงการ และพร้อมเดินหน้าวางแผนขยายผลการดำเนินงานในระยะต่อไป',
    journey_year_2_4_title: 'ปีที่ 2 - 4 (พ.ศ. 2566 - 2568)',
    journey_phase_2_4: 'บ่มเพาะแกนนำและความพร้อมสู่เครือข่าย',
    journey_desc_3_1:'เนื่องจากการใช้ครูพี่เลี้ยงชาวต่างชาติมีต้นทุนสูง โครงการจึงตระหนักถึงความยั่งยืนในระยะยาว ในปีที่ 2 (พ.ศ. 2566) จึงได้คัดเลือกครูที่มีศักยภาพจากรุ่นแรกมาเข้ารับการพัฒนาเป็น "ครูพี่เลี้ยงวิจัย (Teacher-Research Mentor)" โดยได้รับเกียรติจาก Professor Dr. Richard Smith ผู้เชี่ยวชาญชาวอังกฤษมาถ่ายทอดองค์ความรู้',
    journey_desc_3_2:'ตลอดระยะเวลา 3 ปีนี้ ครูพี่เลี้ยงได้ทำหน้าที่ให้คำปรึกษาแก่เพื่อนครู ส่งผลให้โครงการสามารถขยายผลการอบรมครอบคลุมถึง 40 จังหวัดทั่วประเทศ ทำให้มีสมาชิกและครูพี่เลี้ยงกระจายตัวอยู่ตามภูมิภาคต่างๆ อย่างทั่วถึง จนกระทั่งเตรียมพร้อมสู่การยกระดับความร่วมมือครั้งสำคัญ',
    journey_year_5_6_title: 'ปีที่ 5 - 6 (พ.ศ. 2569 - 2571)',
    journey_phase_5_6: 'กำเนิดเครือข่าย TReN และการขับเคลื่อนระดับประเทศ',
    journey_desc_4_1: 'จากการเติบโตของกลุ่มครูนักวิจัยทั่วประเทศ นำมาสู่การก่อตั้ง "เครือข่าย Teacher-Research Network (TReN)" อย่างเป็นทางการ',
    journey_bullet_4_1_strong: 'ยกระดับเครือข่ายเชิงพื้นที่:',
    journey_bullet_4_1_desc: 'ขยายผลผ่านชุมชนนักปฏิบัติระดับภูมิภาค (Regional CoP - EARC) แบ่งเป็น 8 โซนทั่วประเทศ (ภาคกลาง, ภาคเหนือตอนบน-ล่าง, ภาคตะวันออกเฉียงเหนือตอนบน-ล่าง, ภาคตะวันออก และภาคใต้ตอนบน-ล่าง)',
    journey_bullet_4_2_strong: 'พัฒนาศักยภาพครูพี่เลี้ยง:',
    journey_bullet_4_2_desc: 'สู่ระดับสูง (Advanced Level) ด้านภาวะผู้นำและการบริหารจัดการ เพื่อให้แต่ละภูมิภาคพึ่งพาตนเองได้ โดยมี TReN ส่วนกลางคอยหนุนเสริม',
    journey_future_title: 'พ.ศ. 2571 เป็นต้นไป',
    journey_phase_future: 'ขยายผลสู่ความยั่งยืนระดับประเทศ',
    journey_desc_5_1: 'ขยายผลกระบวนการวิจัย EAR สู่ครูทั่วประเทศผ่านเครือข่าย TReN พร้อมทั้งประเมินผลกระทบเชิงลึก (Impact Analysis) เพื่อวัดการเปลี่ยนแปลงที่เกิดขึ้นต่อตัวครู ห้องเรียน นักเรียน และชุมชนอย่างเป็นรูปธรรม',

    journey_intro_desc_new: 'จากจุดเริ่มต้นสู่เครือข่ายวิจัยระดับประเทศ (พ.ศ. 2565 - ปัจจุบัน)',
    // Phase 1: จุดกำเนิด (พ.ศ. 2565)
    journey_year_1_title_new: 'พ.ศ. 2565',
    journey_phase_1_new: 'จุดกำเนิด',
    journey_tren_brand: 'TReN',
    journey_desc_1_1_new: 'เกิดจากความร่วมมือระหว่าง British Council Thailand และ คณะศิลปศาสตร์ มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี (มจธ.) ที่มุ่งติดอาวุธให้ครูประจำการสามารถวิเคราะห์และแก้ปัญหาในชั้นเรียนได้ด้วยตนเอง เพราะบริบทของแต่ละห้องเรียนมีความแตกต่างกัน การรอคอยความช่วยเหลือจากภายนอกหรือการตัดสินใจแก้ปัญหาด้วยความรู้สึกส่วนตัวจึงไม่ยั่งยืน',
    journey_key_takeaway_new: 'Evidence-based decision',
    journey_desc_1_2_new: 'โครงการจึงส่งเสริมหลักคิดการตัดสินใจบนพื้นฐานของประจักษ์พยาน ผ่านกระบวนการ Exploratory Action Research (EAR) เพื่อให้ครูแก้ปัญหาได้ตรงจุดและสอดคล้องกับเกณฑ์พัฒนาวิชาชีพของ ก.ค.ศ.',

    // Phase 2: ปีที่ 1 (พ.ศ. 2565)
    journey_year_2_title_new: 'ปีที่ 1: พ.ศ. 2565',
    journey_phase_2_new: 'จุดประกายและวางรากฐาน',
    journey_desc_2_1_new: 'นำโมเดลการวิจัย EAR ระดับโลกของ Prof. Dr. Richard Smith (University of Warwick) และ Dr. Paula Rebolledo มาใช้อบรมครูภาษาอังกฤษรุ่นแรก 21 คน โดยมีผู้เชี่ยวชาญและครูพี่เลี้ยงนานาชาติคอยประกบดูแลอย่างใกล้ชิด ซึ่งการมีครูพี่เลี้ยงหนุนเสริมนี้ถือเป็นหัวใจสำคัญของความสำเร็จ ดังที่ ดร.สุวิมล ว่องวาณิช ได้สะท้อนไว้อย่างน่าสนใจว่า:',
    journey_quote_new: '"กระบวนการต่างๆ ที่ใช้ในการทำวิจัย เป็นเรื่องที่ครูไม่คุ้นเคย เข้าใจยาก และต้องอาศัยการฝึกปฏิบัติภายใต้พี่เลี้ยงที่เข้าใจในวิธีการวิจัยอย่างสม่ำเสมอ..."',
    journey_quote_author_new: '— (สุวิมล ว่องวาณิช, 2550, น. 6)',
    journey_desc_2_2_new: 'เมื่อจบโครงการ ครูไม่เพียงมีทัศนคติที่ดีขึ้นต่อการทำวิจัย แต่ยังสามารถแก้ปัญหาในห้องเรียนได้ตรงจุด พร้อมทั้งสร้างความสัมพันธ์ที่แน่นแฟ้นยิ่งขึ้นกับนักเรียน (Dersingh & Vuong, 2023)',

    // Phase 3: ปีที่ 2 - 4 (พ.ศ. 2566 – 2568)
    journey_year_3_title_new: 'ปีที่ 2 – 4: พ.ศ. 2566 – 2568',
    journey_phase_3_new: 'บ่มเพาะแกนนำสู่ 40 จังหวัด',
    journey_desc_3_1_new: 'เพื่อสร้างความยั่งยืนและลดการพึ่งพาผู้เชี่ยวชาญต่างชาติ โครงการจึงคัดเลือกครูรุ่นแรกมาพัฒนาต่อยอดเป็น ',
    journey_mentor_role: '"ครูพี่เลี้ยงวิจัย (Teacher-Research Mentor)"',
    journey_desc_3_2_new: ' โดยได้รับเกียรติจาก Prof. Dr. Richard Smith มาถ่ายทอดองค์ความรู้โดยตรง จนกลุ่มครูพี่เลี้ยงแกนนำนี้สามารถขยายผลให้คำปรึกษาแก่เพื่อนครู ครอบคลุมถึง 40 จังหวัดทั่วประเทศ',

    // Phase 4: ปีที่ 5 - 6 (พ.ศ. 2569 เป็นต้นไป)
    journey_year_4_title_new: 'ปีที่ 5 - 6 เป็นต้นไป: พ.ศ. 2569 เป็นต้นไป',
    journey_phase_4_new: 'ก่อตั้ง TReN และขยายผลทั่วประเทศ',
    journey_desc_4_1_new: 'จากความแข็งแกร่งของกลุ่มครูวิจัยและครูพี่เลี้ยงทั่วประเทศ จึงนำไปสู่การก่อตั้ง ',
    journey_tren_network: 'เครือข่าย TReN (Teacher-Research Network)',
    journey_desc_4_2_new: ' อย่างเป็นทางการ โดยขับเคลื่อนผ่านชุมชนนักปฏิบัติระดับภูมิภาค (EART Communities: EARC) แบ่งเป็น 8 โซนทั่วประเทศ ควบคู่กับการยกระดับครูพี่เลี้ยงสู่ระดับสูง (Advanced Level) เพื่อให้แต่ละพื้นที่สามารถพึ่งพาตนเองได้ในระยะยาว พร้อมมุ่งขยายผลกระบวนการ EAR สู่ครูทั่วประเทศและประเมินผลกระทบเชิงลึกอย่างยั่งยืน',

    // สรุปตัวเลขการเติบโต (Table)
    journey_table_main_title: 'สรุปตัวเลขการเติบโตของเครือข่าย',
    journey_table_col1: 'ดัชนีชี้วัด',
    journey_table_col1_en: '(Key Indicator)',
    journey_table_col2: 'ตัวเลขความสำเร็จ',
    journey_table_col3: 'รายละเอียดการขยายผล',

    // สถิติตาราง
    journey_stat_1_name: 'ครูประจำการที่ได้รับการพัฒนา',
    journey_stat_1_val: '280 คน',
    journey_stat_1_desc: 'จากรุ่นนำร่อง 21 คน สู่การแก้ปัญหาในชั้นเรียนด้วย EAR ทั่วประเทศ',

    journey_stat_2_name: 'ครูพี่เลี้ยงวิจัย',
    journey_stat_2_en: '(Mentors)',
    journey_stat_2_val: '50 คน',
    journey_stat_2_desc: 'บ่มเพาะจากครูแกนนำรุ่นแรก สู่ผู้เชี่ยวชาญที่คอยหนุนเสริมเพื่อนครู',

    journey_stat_3_name: 'พื้นที่การทำงาน',
    journey_stat_3_val: '40 จังหวัด',
    journey_stat_3_desc: 'กระจายเครือข่ายการเรียนรู้และการดูแลอย่างทั่วถึงทุกภูมิภาค',

    journey_stat_4_name: 'ชุมชนนักปฏิบัติ',
    journey_stat_4_en: '(EARCs)',
    journey_stat_4_val: '8 โซน',
    journey_stat_4_desc: 'ยกระดับเครือข่ายเชิงพื้นที่ให้พึ่งพาตนเองได้อย่างยั่งยืน',

    // อ้างอิงท้ายตาราง
    journey_ref_author: '* สุวิมล ว่องวาณิช. (2550).',
    journey_ref_book: 'การวิจัยปฏิบัติการในชั้นเรียน',
    journey_ref_pub: '(พิมพ์ครั้งที่ X). สำนักพิมพ์แห่งจุฬาลงกรณ์มหาวิทยาลัย.',

    // Core Role & Missions Page //
    role_main_title: 'บทบาทและภารกิจหลัก',
    role_subtitle: 'TReN Core Roles & Missions',
    role_intro_headline:'องค์กรสนับสนุนหลัก',
    role_intro_headline_en: '(Supporting Body)',
    role_intro_p1:'TReN ทำหน้าที่เป็น องค์กรสนับสนุนหลัก (Supporting Body) เพื่อสร้างความยั่งยืนให้แก่ระบบการพัฒนาครูอย่างแท้จริง โดยมุ่งเน้นการส่งเสริมและสนับสนุนให้ครูไทยสามารถวิเคราะห์และแก้ไขปัญหาในชั้นเรียนได้ด้วยตนเองผ่านกระบวนการ Exploratory Action Research (EAR)',
    role_intro_p2:'TReN ยึดเอา ชุมชน EAR Community (EARC) ในระดับพื้นที่เป็นหัวใจสำคัญ และเข้ามาบริหารจัดการความยั่งยืนด้วยการส่งเสริม หนุนเสริม และสร้างความเข้มแข็ง ให้ชุมชน EARC ในแต่ละภูมิภาคสามารถบริหารจัดการตนเอง พัฒนาศักยภาพสมาชิกด้านการทำวิจัย EAR ได้อย่างต่อเนื่อง พร้อมทั้งขยายผลการอบรมให้ครอบคลุมครูทั่วประเทศได้อย่างพึ่งพาตนเองได้ในระยะยาว',
    role_intro_bridge: 'โดยขับเคลื่อนภารกิจผ่าน 3 เสาหลัก ได้แก่:',
    role_pillar_prefix: 'เสาหลักที่',

    role_pillar_1_title: 'ด้านการพัฒนาศักยภาพและยกระดับวิชาการ',
    role_pillar_1_en: '(Capacity Building & Mentor Training)',
    role_p1_item1_name: 'การอบรมการทำวิจัยในชั้นเรียนระดับชาติ (Centralized EAR Workshop)',
    role_p1_item1_desc: 'จัดการอบรมส่วนกลางปีละ 1–2 ครั้ง เพื่อสร้างมาตรฐานการทำวิจัยปฏิบัติเชิงสำรวจ EAR และขยายโอกาสให้ครูในพื้นที่ห่างไกลเข้าถึงกระบวนการพัฒนาตนเอง',
    role_p1_item2_name: 'การพัฒนาศักยภาพครูพี่เลี้ยงขั้นสูง (Mentor Advanced Training)',
    role_p1_item2_desc: 'จัด Workshop เติมทักษะขั้นสูง (เช่น Co-coaching และ Advanced Reflective Practice) ให้แก่กลุ่มครูพี่เลี้ยงเดิม ควบคู่กับการบ่มเพาะครูพี่เลี้ยงรุ่นใหม่เพื่อรองรับการขยายตัวของเครือข่าย',
    role_p1_item3_name: 'การเสวนาวิชาการออนไลน์ (TReN Webinar Series)',
    role_p1_item3_desc: 'จัดสัมมนาออนไลน์อย่างต่อเนื่องเพื่อพัฒนาองค์ความรู้ใหม่ โดยเชิญผู้เชี่ยวชาญจากสถาบันอุดมศึกษา, British Council และ RELO ร่วมถ่ายทอดแนวโน้มการจัดการเรียนรู้ยุคใหม่',

    role_pillar_2_title: 'ด้านการบริหารเครือข่ายและการติดตามประเมินผล',
    role_pillar_2_en: '(Governance & Network Management)',
    role_p2_item1_name: 'การประชุมติดตามผลและวางยุทธศาสตร์เครือข่ายระดับชาติ (Annual EARC Review & Strategy Meeting / TReN Retreat)',
    role_p2_item1_desc: 'เวทีสำหรับตัวแทน EARC เข้ามารายงานผลการดำเนินงาน แลกเปลี่ยนความท้าทาย และเข้ารับการเติมเต็มทักษะใหม่ (Retraining) เพื่อนำกลับไปขับเคลื่อนพื้นที่ตนเองได้อย่างเข้มแข็งและพึ่งพาตนเองได้',
    role_p2_item2_name: 'การติดตามและประเมินผลเชิงลึก (Impact Analysis)',
    role_p2_item2_desc: 'ประเมินและติดตามผลกระทบของการทำวิจัย EAR อย่างเป็นรูปธรรม ทั้งในมิติการเปลี่ยนแปลงของตัวครู ห้องเรียน นักเรียน และชุมชน เพื่อนำข้อมูลมาใช้ปรับปรุงยุทธศาสตร์การพัฒนาการศึกษาในระยะยาว',
  
    role_pillar_3_title: 'ด้านการเผยแพร่ผลงานและเชื่อมโยงสู่สากล',
    role_pillar_3_en:'(Dissemination, Impact Analysis & Internationalization)',
    role_p3_item1_name: 'การประชุมวิชาการระดับชาติและภูมิภาค (EAR Conference)',
    role_p3_item1_desc: 'จัดเวทีนำเสนอผลงานวิจัยในชั้นเรียน (ทั้งรูปแบบ Oral และ Poster Presentation) เพื่อส่งเสริมความก้าวหน้าทางวิชาชีพและสร้างความภาคภูมิใจให้แก่ครูในเครือข่าย',
    role_p3_item2_name: 'โครงการแลกเปลี่ยนวิจัยเชิงปฏิบัติการระดับภูมิภาค (Cross-Border AR Fellowship Program)',
    role_p3_item2_desc: 'ผนึกกำลังร่วมกับ British Council และ RELO ในการขยายผลกระบวนการ EAR สู่ประเทศเพื่อนบ้าน (ลาว กัมพูชา เวียดนาม และเมียนมา) พร้อมผลักดันให้ครูพี่เลี้ยงไทยก้าวสู่การเป็นผู้เชี่ยวชาญและให้คำปรึกษาในระดับภูมิภาค',
  
    // Governance & Charter Page //
    governance_main_title:'กรอบการทำงาน',
    governance_subtitle:'Governance & Charter',
    governance_doc_title: 'ธรรมนูญเครือข่าย (TReN Charter)',
    governance_doc_desc: 'เอกสารกำหนดกรอบการทำงานของเครือข่าย TReN เพื่อให้เกิดความเข้าใจร่วมกันและสร้างความยั่งยืนในการดำเนินงาน',
    governance_btn_download: 'ดาวน์โหลดเอกสาร',

    // Supporter Page //
    sponsor_british_council: 'British Council ประเทศไทย',
    sponsor_relo: 'Regional English Language Office (RELO) สถานเอกอัครราชทูตสหรัฐอเมริกา',
    sponsor_kmutt: 'มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี (มจธ.)',
    sponsor_earc: 'เครือข่ายชุมชนนักปฏิบัติ (EAR Community - EARC)',
    sponsor_obec:'สำนักวิชาการและมาตรฐานการศึกษา สำนักงานคณะกรรมการการศึกษาขั้นพื้นฐาน (สพฐ.) กระทรวงศึกษาธิการ',
    sponsor_ptt: 'บริษัท ปตท. จำกัด (มหาชน)',
    sponsor_eef: 'กองทุนเพื่อความเสมอภาคทางการศึกษา (กสศ.)',
    sponsor_earc_desc: 'เครือข่ายครูนักวิจัยในชั้นเรียนที่เกิดขึ้นจากการรวมตัวของครูผู้เข้าร่วมโครงการ TReN ในแต่ละภูมิภาค เพื่อแลกเปลี่ยนเรียนรู้และสนับสนุนซึ่งกันและกัน',
    
    sponsors_main_title: 'องค์กรพันธมิตรและผู้สนับสนุน',
    sponsors_subtitle: 'Our Partners & Sponsors',
    sponsors_intro: 'ความสำเร็จและการเติบโตอย่างยั่งยืนของเครือข่าย TReN เกิดขึ้นได้ด้วยวิสัยทัศน์และการสนับสนุนอันทรงคุณค่าจากองค์กรพันธมิตรทุกภาคส่วน ที่ร่วมผสานพลังในการพัฒนาศักยภาพครูไทย และยกระดับคุณภาพการศึกษาอย่างต่อเนื่อง',
    sponsors_thank_you: 'ทางเครือข่าย TReN ขอขอบพระคุณองค์กรพันธมิตรทุกแห่งเป็นอย่างยิ่ง:',
    sponsors_outro: 'ทุกการสนับสนุนคือพลังสำคัญในการขับเคลื่อนครูไทยสู่การเป็นผู้นำการเปลี่ยนแปลง เพื่อส่งต่อการเรียนรู้ที่มีคุณภาพให้แก่นักเรียนทั่วประเทศ',

  },
  en: {
    translating: 'Translating...',
    
    // Login Modal
    login_tab: 'Log In',
    register_tab: 'Register',
    password: 'Password',
    remember_me: 'Remember me',
    forgot_password: 'Forgot password?',
    school_province_placeholder: 'School Province',
    teacher_rank_placeholder: 'Teacher Academic Rank',
    processing: 'Processing...',
    login_success: 'Login successful!',
    account_suspended: 'Your account has been suspended',
    unknown_error: 'An unknown error occurred',
    register_success: 'Registration successful!',

    // Footer
    copyright: 'Copyright © 2026 - TReN.org',
    languageLabel: 'Language :',

    // Password Update Page //
    back_to_home: 'Back to Home',
    update_password_title: 'Update Password',
    update_password_desc: 'Please set a new password for your account',
    new_password: 'New Password',
    confirm_new_password: 'Confirm New Password',
    confirm_password_placeholder: 'Please enter your new password again',

    invalid_reset_link: 'Invalid or expired password reset link',
    password_min_length: 'Password must be at least 6 characters long',
    password_mismatch: 'New password and confirmation password do not match',
    password_update_success: 'Password updated successfully! You can now log in with your new password.',
    password_update_error: 'An error occurred while updating the password. Please try again.',
    password_min_length_hint: 'At least 6 characters',
    error_same_password: 'New password cannot be the same as the old password',
    error_weak_password: 'Password is too weak. Please choose a stronger password.',

    // Navbar 
    home: 'Home',
    events: 'Events',
    blogs: 'Blogs',
    resources: 'EAR Resources',
    showcases: 'Showcases',
    about: 'About Us',

    // Navbar Dropdown 
    profile: 'Profile',
    adminDashboard: 'Admin Dashboard',
    logout: 'Log out',
    upcoming_events_navbar: 'Upcoming Events',
    past_events_navbar: 'Past Events',
    history_about_us: 'History',
    timeline_about_us: 'TReN Timeline',

    history_of_ear_about_us: 'EAR History',
    organization_about_us: 'Organizational Structure',
    mission_about_us: 'Our Mission',
    vision_mission_objectives_about_us: 'Vision, Mission and Core Objectives',
    history_of_tren_about_us: 'History of TReN',
    ear_team_about_us: 'EAR Team',
    constitution_about_us: 'Constitution',
    supporter_about_us: 'Our Partners & Sponsors',

    core_principles_about_us: 'Core Principles',
    tren_journey_about_us:' TReN Journey',
    core_role_about_us: 'Core Role & Missions',
    governance_about_us: 'Governance & Charter',

    // Profile Page
    profile_title: 'My Profile',
    edit_profile: 'Edit Profile',
    published: 'Published',
    in_progress: 'In Progress',
    edit: 'Edit',
    no_contents_desc: 'No content created yet',
    no_pending_contents_desc: 'No pending content at the moment',
    loading_profile: 'Loading profile...',

    edit_profile_save: 'Save Changes',
    edit_profile_saving: 'Saving...',
    edit_profile_cancel: 'Cancel',
    save_success: 'Changes saved successfully!',
    save_error: 'An error occurred while saving changes',
    edit_profile_title: 'Edit Profile',
    edit_profile_change_photo: 'Change Profile Photo',
    first_name: 'First Name',
    last_name: 'Last Name',
    select_province: 'Select Province',
    select_position: 'Select Position',
    select_rank: 'Select Academic Rank',
    teacher: 'Teacher',
    assistant_teacher: 'Assistant Teacher',
    cannot_change_email: 'Cannot change email',
    password_label: 'New Password (leave blank if not changing)',
    bio: 'Bio',
    view_rejection_reason: 'View Reason',
    delete: 'Delete',
    rejection_reason: 'Rejection Reason',
    close: 'Close',
    status_rejected: 'Rejected',
    deleting: 'Deleting...',
    confirm_delete: 'Confirm Delete',
    are_you_sure_you_want_to_delete: 'Are you sure you want to delete',
    this_action_cannot_be_undone: 'This action cannot be undone',

    create_blog: 'Create Blog',
    create_event: 'Create Event',
    create_showcase: 'Create Showcase',
    create_news: 'Create News',

    delete_success: 'Deleted successfully!',

    // Create Event Page
    create_event_title: 'Create an Event',
    create_event_desc: 'Create an event schedule for people to attend.',
    creat_event_name: 'Event Name',
    event_date: 'Date',
    event_time: 'Time',
    event_location: 'Location',   
    event_brief_description: 'Brief Description',
    add_image_cover: 'Add Image Cover',
    post_event_details: 'Post Event Details',
    about_event: 'About Event',
    conclude_info: 'Conclude Information',
    resource_link: 'Resource Links',
    attach_media: 'Attach Media',
    up_to_links: 'Up to 2 links allowed',
    event_submit_btn: 'Create Event',
    event_creating: 'Creating...',
    create_event_success: 'Create Event Success!',
    create_event_error: 'An error occurred while creating the event',

    update_event_success: 'Update Event Success!',
    update_event_error: 'An error occurred while updating the event',
    edit_event_title: 'Edit Event',
    event_save_changes: 'Save Changes',

    file_size_exceeded: 'File size exceeded (max 5MB)',
    invalid_file_type: 'Invalid file type (only .jpg, .jpeg, .png supported)',
    edit_event_success_pending: 'Changes saved successfully! Please wait for review by the team.',
    edit_event_success: 'Changes saved successfully!',

    add_link: 'Add Link',
    no_permission: 'You do not have permission to access this page',

    // Comment Section
    share_comments: 'Share your comments',
    no_comments_yet: 'No comments yet. Be the first to comment!',
    leave_a_reply: 'leave a reply',
    write_a_comment: 'write a comment here...',
    post_comment: 'Post Comment',
    must_log_in_to_comment: 'You must be logged in to comment',
    post: 'Post',
    reply: 'Reply',
    comment_delete: 'Delete',
    view_replies: 'View Replies',

    confirm_delete_comment: 'Are you sure you want to delete this comment?',
    are_you_sure_you_want_to_delete_comment: 'This delete will delete the comment and all its replies.',
    delete_comment_warning: 'This action cannot be undone',

    // Blog Detail Page
    success: 'success',
    error: 'error',
    ok: 'okay',
    no_permission_blog: 'You do not have permission to access this content',
    link_copied: 'Link copied!',
    preview_warning: 'You are viewing a preview (Preview) | Current Status:',
    status_in_progress: 'Draft (In Progress)',
    share_post: 'Share this post',
    no_bio: 'The author has not added a biography yet (Bio)',
    more_posts: 'View more',
    related_blogs: 'Related Blogs',
    view_all: 'View All',
    by_author: 'By',
    read_more: 'Read More',
    loading_blogs: 'Loading blogs...',
    blog_not_found: 'Blog not found',

    // Create Blog Page
    msg_edit_pending: 'Blog submitted for review!',
    msg_edit_success: 'Successfully edited!',
    msg_create_success: 'Successfully created blog!',
    msg_edit_draft: 'Successfully updated draft!',
    msg_edit_published: 'Successfully saved!',

    msg_create_pending: 'Blog submitted for review!',
    msg_create_error: 'An error occurred while creating the blog',
    msg_edit_error: 'An error occurred while editing the blog',
    msg_create_draft: 'Draft created successfully!',
    msg_create_published: 'Blog published successfully!',

    loading_blogs_editor: 'Loading Editor...',
    enter_blog_title: 'Enter Blog Title...',
    start_writing: 'Start Writing your content here...',
    back_to_dashboard: 'Back to Dashboard',
    save_changes: 'Save Changes',
    publish: 'Publish',
    save_draft: 'Save Draft',
    click_change_image: 'Click to change image',
    add_blog_cover: 'Add blog cover image here.',
    press_enterToAddTag: 'Press Enter or click "Add" to create tag',
    category_and_tags: 'Category & Tags',
    add_tag: 'add tag',
    delete_tag: 'delete tag',
    add_tags: 'Add tags...',
    add_more_tags: 'Add more tags...',

    as_new_tag: 'as a new tag: ',
    tag_input_hint: '* Search for existing tags or type a new tag and press Enter to add',
    link_title: 'Resource link, Slide URL, or YouTube/Vimeo URL',

    // All Blogs Page
    teacher_blogs: 'Teacher\'s Blogs',
    all_teachers_blogs: 'Teacher\'s Blogs',
    search_explore_blogs: 'Search and explore all blogs here',
    search_blogs_placeholder: 'Search by author, blog, or tags...',
    next: 'Next',
    no_blogs_found: 'No blogs found',
    no_blogs_found_desc: 'No articles found that match your search or category',
    all: 'All',
    tag_research: 'Research',
    tag_tips: 'Tips',
    tag_teaching: 'Teaching',
    tag_innovation: 'Innovation',
    tag_other: 'Other',
    no_image: 'No image',

    // Create Showcase Page
    require_title: 'Please fill the title',
    require_login: 'You must be logged in to create a showcase',
    require_description: 'Please fill the description',
    create_showcase_success: 'Showcase created successfully!',
    edit_showcase_pending: 'Showcase changes submitted for review!',
    edit_showcase_success: 'Showcase updated successfully!',
    create_showcase_published: 'Showcase published successfully!',
    error_saving: 'An error occurred while saving the showcase',
    create_showcase_error: 'An error occurred while creating the showcase',
    edit_showcase_error: 'An error occurred while editing the showcase',
    create_showcase_title: 'Create Showcase',
    edit_showcase_title: 'Edit Showcase',
    save_showcase_changes: 'Save Changes',
    create_showcase_desc: 'Share your other works with other teachers.',
    create_showcase_title_name: 'Title',
    create_showcase_author: 'Author(s)',
    create_showcase_description: 'Description',
    create_showcase_add_image: 'Add Image cover',
    link_to_work: 'Link to your work',
    create_showcase_image_desc: 'You can add an image to showcase your work (optional)',
    showcase_brief_description: 'Brief Description',
    change_media: 'Change Media',
    create_showcase_btn: 'Create Showcase',
    published_date: 'Date Published',
    visit_work: 'Visit the work',
    edit_showcase_published: 'Changes saved successfully!',
    create_showcase_pending: 'Your showcase has been submitted for review',
    create_showcase_author_hint: 'Search for teacher name in the system or type the name and press Enter to add',
    searching: 'Searching...',
    add: 'Add',
    no_links_provided: 'No links provided for this showcase',
    

    // All Events Page
    all_events: 'All Events',
    search_explore_events: 'Search and explore all events here',
    search_events_placeholder: 'Search by event name or keyword..',
    previous: 'Previous',
    no_events_found: 'No events found',
    no_events_found_desc: 'No events found that match your search or category',
    all_event_date: 'Date',
    all_event_time: 'Time',
    all_event_place: 'Place',
    all_event_no_brief_description: 'No brief description available',

    filter_all: 'All',
    filter_upcoming: 'Upcoming',
    filter_past: 'Past',
    filter_done: 'Done',

    // All Showcases Page
    showcases_menu: 'Showcases',
    all_showcases_title: 'All Showcases',
    search_explore_showcases: 'Search and explore all showcases here',
    search_showcases_placeholder: 'Search by title, author, or keyword..',
    no_showcases_found: 'No showcases found',
    no_showcases_found_desc: 'No showcases found that match your search or category',
    explore_showcases_desc: 'Explore showcases created by teachers to get inspiration for your own work!',
    tag_article: 'Article',
    tag_presentation: 'Presentation',

    // Admin Dashboard Sidebar
    menu: 'Menu',
    admin_menu: 'Admin Menu',
    overview: 'Overview',
    blog: 'Blogs',
    event: 'Events',
    showcase: 'Showcases',
    resource: 'Resources',
    reports: 'Reports',
    users: 'Users',
    search: 'Search...',
    status: 'Status',

    // Admin Dashboard Table
    type: 'Type',
    titleSubject: 'Title/Subject',
    submittedBy: 'Submitted by',
    date: 'Date',
    view: 'View details',
    action: 'Actions',

    // Admin Dashboard Overview
    dashboard: 'Dashboard Overview',
    pendingRequests: 'Pending Requests',
    reports_overall: 'Reports',
    totalUsers: 'Total Users',
    recentPendingRequests: 'Recent Pending Requests',
    only_admin_can_perform_this_action: 'Only admin',
    type_report: 'Report',
    type_blog: 'Blog',
    type_event: 'Event',
    type_showcase: 'Showcase',
    loading: 'Loading...',
    showing: 'Showing',
    to: 'to',
    from: 'from',
    list: 'list',
    page: 'Page',

    // Admin Blogs
    blog_title: 'Blogs Dashboard',
    no_blogs: 'No blogs found.',
    reject_blog_title: 'Reject Blog Content',
    reject_blog_reason: 'Please provide a reason :',
    reject_blog_placeholder: 'Ex. Inappropriate content / Incomplete information...',
    confirm_reject: 'Confirm',
    delete_blog_success: 'Blog deleted successfully',

    // Admin Events
    event_title: 'Events Dashboard',
    no_events: 'No events found.',
    event_actions: 'Actions',
    done: 'Mark as Done',
    event_status: 'Event Status',
    publish_state: 'Publish State',
     status_upcoming: 'Upcoming',
    status_past: 'Past',
    status_done: 'Done',
    state_pending: 'Pending',
    state_published: 'Published',
    state_rejected: 'Rejected',
    create_date: 'CreateDate',
    admin_events_confirm_approve: 'Are you sure you want to approve this event?',
    admin_events_confirm_mark_as_done: 'Are you sure you want to mark this event as "Done" ?',
    admin_events_mark_as_done_success: 'The event has been marked as Done successfully.',
    admin_events_approve_success: 'The event has been approved for publication.',
    error_updating_event_occurred: 'An error occurred while updating the event.',
    confirm: 'Confirm',
    cancel: 'Cancel',
    loading_events: 'Loading events...',
    view_event_details: 'View Event Details',
    approve: 'Approve',
    delete_event_success: 'Event deleted successfully',

    // Admin Showcases
    showcase_title: 'Showcases Dashboard',
    no_showcases: 'No showcases found.',
    loading_showcases: 'Loading showcases...',

    // Admin Reports
    report_title: 'Reports Dashboard',
    no_reports: 'No reports found.',
    loading_reports: 'Loading reports...',
    resolved: 'Resolved',
    ticket_inquiry: 'Inquiry',
    ticket_bug: 'Bug',
    ticket_comment: 'Report',
    report_category: 'Category',

    report_desc: 'Description',
    reporter: 'Reporter',
    report_date: 'Report Date',
    admin_note: 'Admin Note',
    view_source: 'View Source',

    confirm_resolved: 'Confirm Resolved',
    confirm_resolved_message: 'You are updating the status of',
    resolve_modal_placeholder: 'For example, I have removed this block from the system, I have temporarily banned the user...',
    save_report_status: 'Save Status',
    confirm_reject_message: 'You are rejecting the report',
    reject_reason: 'Reason for Rejection',
    reject_modal_placeholder: 'For example, after checking, no violation was found, insufficient information...',
    save_rejection: 'Save Rejection',
    delete_report_success: 'Report deleted successfully',
    report_pending: 'Pending',

    // Admin Users
    no_users: 'No users found.',
    id: 'Id',
    profile_pic: 'Profile Pic',
    name: 'Name',
    role: 'Role',
    joined_date: 'Joined Date',
    email: 'Email',
    school: 'School',
    province: 'Province',
    position: 'Position',
    academic_rank: 'Academic Rank',
    total_blogs: 'Total Blogs',
    total_showcases: 'Total Showcases',
    ban_user: 'Ban User',
    user: 'Users',
    account_details: 'User Details',
    post_count: 'Post',
    showcase_count: 'Works',

    confirm_ban: 'Confirm Ban',
    confirm_ban_message: 'You are banning user',
    confirm_unban: 'Confirm Unban',
    confirm_unban_message: 'You are unbanning user',
    unban_user: 'Unban User',
    are_you_sure_you_want_to_ban: 'Are you sure you want to ban this user?',
    user_banned_successfully: 'User banned successfully',
    user_unbanned_successfully: 'User unbanned successfully',
    this_user_login_disabled: 'This user will not be able to log in until they are unbanned',
    are_you_sure_you_want_to_unban: 'Are you sure you want to unban this user?',
    banned: 'Banned',

    // Confirmation Box Approve/Reject
    confirm_approve: 'Confirm Approval',
    confirm_approve_message: 'Are you sure you want to approve',
    content_will_be_published: 'This content will be published to the public',
    no_pending_requests: 'No pending requests',
    reject: 'Reject',

    // Report Modal
    report_modal_title: 'Report Issue',
    report_modal_desc: 'Report inappropriate or violating content',
    report_modal_category: 'Report Category',
    report_category_inappropriate: 'Inappropriate / Offensive Content',
    report_category_copyright_infringement: 'Copyright Infringement',
    report_category_spam_ads: 'Spam / Hidden Ads',
    report_category_false_information: 'False Information / Misleading',
    report_category_broken_links: 'Broken Links / Unavailable',
    report_category_other: 'Other',
    report_modal_description: 'Additional Details',
    report_modal_placeholder: 'Please describe the issue you found...',
    submit_report: 'Submit Report',
    report_submitted_success: 'Report submitted successfully!',
    report_submitted_error: 'An error occurred while submitting the report',
    report_success: 'Success',
    report_error: 'Error',

    // Search Page
    find_info_you_need: 'Find the information you need',
    No_results_found: 'No results found for',
    try_different_keywords: 'Try different keywords or browse all content',
    found: 'Found',
    found_for: 'items for',

    // Resource Page
    all_resources: 'All Resources',
    resources_desc: 'Search and explore all resources here',
    add_resource: 'Add Resource',
    search_resources: 'Search resources by name or keyword...',
    loading_resources: 'Loading resources...',
    no_resources_found: 'No resources found',
    no_resources_found_desc: 'No resources found matching your search or category selection',
    view_details: 'View Details',
    resource_title: 'Resource Title',
    resource_category: 'Category',
    try_different_resource_keywords: 'Try different search keywords or browse all content',

    filter_document: 'Documents',
    filter_media: 'Images & Videos',
    filter_folder: 'Folders',
    filter_link: 'Website Links',
    resource_edit_success: 'Edit successfully',
    resource_create_success: 'Create successfully',
    resource_delete_success: 'Delete successfully',

    edit_resource_title: 'Edit Resource',
    create_resource_title: 'Create Resource',
    create_resource_desc: 'Add files, documents, or videos to share with others',
    resource_type: 'Resource Type',
    resource_placeholder: 'e.g., Webinar video, Teaching materials...',
    resource_url: 'Resource URL',
    resource_description: 'Resource Description',
    resource_description_placeholder: 'Please provide a brief description of the resource...',
    create_resource_button: 'Create Resource',
    edit_resource_button: 'Save Changes',
    resource_file_size_exceeded: 'File size exceeds 10MB',
    resource_invalid_file_type: 'Invalid file type (only .jpg, .jpeg, .png, .pdf, .mp4 are supported)',

    added_on: 'Created on: ',
    no_description_provided: 'No description provided',
    open_folder: 'Open Folder',
    view_media: 'View Media',
    open_document: 'Open Document',
    open_link: 'Open Link',

    // Home Page
    home_title: 'Teacher-research Network (TReN)',
    home_subtitle: 'Classroom Research Network for Sustainable Change',
    home_description: 'TReN serves as a hub for driving the development of Exploratory Action Research (EAR) skills through a Community of Practice (CoP) model. It connects networks of mentor teachers and general teachers across eight regions nationwide, aiming to enhance instructional practices and empower teachers to independently resolve classroom challenges.',
    
    our_mission: 'Achievements over the past 5 years',
    three_hundred_plus: '300+',
    registered_teachers: 'Teachers participated',
    over_provinces: 'covers 40 \nprovinces nationwide',
    one_hundred_fifty_plus: '150+',
    research_projects: 'Classroom Research Projects',
    already_published: 'Already published over',
    fifty_research_articles: '50 articles',
    fifty_teachers: '50',
    mentors: 'Research Mentor',
    already_trained: 'who have undergone capacity building and are ready to support fellow teachers in the area.',

    calendar_events: 'Event Calendar',
    events_on: 'Events on',
    target_audience: 'Target Audience',
    target_teacher:'General Teachers',
    target_mentor:'Research Mentors',
    target_everyone:'General Public',
    register_join: 'Register to Join Event',
    no_events_today: 'No events scheduled for today',
    click_other_dates: 'Click to view other dates',

    news: 'News',
    all_news: 'All News',
    search_explore_news: 'Search and explore all news here',
    search_news_placeholder: 'Search by title, author, or keyword...',
    news_announcements: 'Announcements',
    news_earc: 'EARC Spotlight',
    news_activity: 'Activity News',
    no_news: 'No data found',
    view_all_announcements: 'View All Announcements',
    view_all_stories: 'View All Stories',
    view_all_activities: 'View All Activity News',
    loading_news: 'Loading news...',
    related_news: 'Related News',
    admin_approve_news_success: 'News approved successfully',
    error_updating_occurred: 'An error occurred while approving the news',

    // Vision Mission Objectives Page //
    vision_about_tren_title: 'TReN',
    vision_about_tren_subtitle: 'Teacher Research Network',
    vision_about_tren_en_title: 'Teacher-Research Network',
    vision_about_tren_desc: 'We are TReN (Teacher-Research Network), a research network driven by the power of teachers to solve classroom problems on their own. We are committed to developing research skills through the Exploratory Action Research (EAR) process, building Communities of Practice (CoP) or EAR Communities (EARC) across all 4 regions nationwide, and developing a mentorship system to create a sustainable learning ecosystem. We transform classroom problem-solving into impactful research and truly elevate student achievement.',

    vision_about_vision: 'Vision',
    vision_about_vision_desc: '"To be a national classroom research network that drives Thai teachers to use Exploratory Action Research (EAR) to sustainably develop their own teaching and learning, and grow strongly together."',

    vision_about_mission: 'Mission',
    vision_about_mission_subtitle: 'What we are committed to doing to drive education forward',
    vision_about_empowerment: 'Develop Skills',
    vision_about_empowerment_en: 'Empowerment',
    vision_about_empowerment_desc: 'Promote knowledge, understanding, and skills in conducting Exploratory Action Research (EAR) so that teachers can practically apply them to solve problems in the classroom.',
    vision_about_community: 'Build a Network',
    vision_about_community_en: 'Community',
    vision_about_community_desc: 'Expand Communities of Practice (CoP) or EAR Communities (EARC) nationwide as a space for shared learning and exchange.',
    vision_about_sustainability: 'Create Sustainability',
    vision_about_sustainability_en: 'Sustainability',
    vision_about_sustainability_desc: 'Develop a mentorship system and elevate teachers\' potential to ensure that learning management and classroom research can be driven continuously and sustainably.',

    vision_about_core_objectives: 'Core Objectives',
    vision_about_goal_01: 'Goal 01',
    vision_about_goal_02: 'Goal 02',
    vision_about_goal_03: 'Goal 03',
    vision_about_obj1_en: 'Ecosystem & Support',
    vision_about_obj1_th: 'Create a Learning Ecosystem and Support Teachers',
    vision_about_obj1_desc: 'Design curricula and establish a Mentorship system to provide in-depth consultation.',
    vision_about_obj2_en: 'Network & Community',
    vision_about_obj2_th: 'Expand Networks and Learning Exchange Spaces',
    vision_about_obj2_desc: 'Establish CoP (EAR Community - EARC) spaces nationwide and organize learning exchange forums to inspire.',
    vision_about_obj3_en: 'Sustainability & Impact',
    vision_about_obj3_th: 'Drive Sustainability and Implementation',
    vision_about_obj3_desc: 'Create a knowledge repository from Best Practices and push for a genuine research culture in educational institutions.',

    vision_about_vision_headline: 'Vision',
    vision_about_mission_headline: 'Mission',
    vision_about_core_objectives_headline: 'Core Objectives',

    vision_about_tren_desc_1: 'is a research network driven by the power of teachers. We are committed to elevating the potential of Thai teachers to solve classroom problems directly and independently through classroom research called Exploratory Action Research (EAR), which emphasizes using actual data and evidence from the classroom to improve teaching and learning.',
    vision_about_channels_title: 'Learning Channels and Participation',
    vision_about_target_general: 'General Teachers:',
    vision_about_target_general_desc: 'Can independently study the concepts and processes of EAR research through the knowledge repository on this website.',
    vision_about_target_selected: 'Selected Teachers for Training:',
    vision_about_target_selected_desc: 'Will learn the research process step-by-step intensively, with a "Research Mentor" providing guidance and close supervision throughout the research.',
    vision_about_tren_desc_2: 'TReN is a Community of Practice (CoP) that connects teachers across all 4 regions nationwide. We are ready to support and open spaces for teachers to develop professionally, exchange experiences, build friendships with fellow teachers, and join hands to develop Thai education in the future.',
    vision_about_vision_subhead: ' ',
    vision_about_mission_subhead: ' ',
    vision_about_core_objectives_subhead: ' ',
    
    // Core Principles Page //
    principle_1_title: 'Truly driven by teachers, for teachers.',
    principle_1_en: '(Teacher-Led)',
    principle_1_desc: 'Primarily managed and led by school teachers, every decision stems from genuine needs, free from top-down directives.',
    principle_2_title: 'Focus on community and collaboration.ๆ',
    principle_2_en: '(Collaboration)',
    principle_2_desc: 'A community of practice (CoP/EARC) where members are ready to share and support one another in a spirit of mutual goodwill, fostering collective growth.',
    principle_3_title: 'Focusing on the classroom and learner outcomes.',
    principle_3_en: '(Classroom-Based)',
    principle_3_desc: 'Research projects start from real problems and aim to create positive changes for students without focusing on accumulating academic papers.',
    principle_4_title: 'Open-minded and learning together.',
    principle_4_en: '(Open & Reflective)',
    principle_4_desc: 'Create a "safe space" for teachers to openly discuss problems or mistakes in the classroom without fear of judgment, while welcoming teachers from all affiliations.',
    principle_5_title: 'Passing on sustainability',
    principle_5_en: '(Sustainable Mentorship)',
    principle_5_desc: 'Build a knowledge transfer system to develop new mentors and ensure the sustainable growth of the network.',

    about_principles_main: 'TReN’s 5 Core Principles',
    about_principles_subtitle: ' ',
    practice_guideline: 'Guidelines:',

    // TReN Journey Page //
    journey_main_title: 'TReN Journey',
    journey_subtitle: ' ',
    journey_intro_desc: 'From a small beginning in the classroom to driving a national network of teacher-researchers, aiming to sustainably elevate student achievement (2022 - Present).',
    journey_year_1_title: '2022',
    journey_phase_1: 'Origins and Classroom Challenges',
    journey_desc_1_1: 'The Teacher-Research Network (TReN) began as a collaboration between British Council Thailand and the School of Liberal Arts, King Mongkut\'s University of Technology Thonburi (KMUTT). Its primary goal is to equip in-service teachers with the tools to solve classroom problems on their own.',
    journey_desc_1_2: 'In real working life, teachers face various challenges, such as using teaching methods or media that do not align with learners, inefficiencies in learning management, or students\' lack of motivation. Although the government has previously provided support measures—such as sending supervisors to visit classrooms, Professional Learning Community (PLC) policies, or organizing practical training workshops—the contexts and problems of each classroom are entirely different. Waiting for external assistance is simply not enough.',
    journey_key_takeaway: 'A Sustainable Solution',
    journey_desc_1_3: 'It must start with a shift in perspective, adhering to the core principle that every teacher\'s decision must be based on evidence rather than personal feelings (evidence-based decision-making). Often, teachers solve problems based on bias or personal experience, leading to ineffective solutions. Equipping teachers with the intellectual tools to analyze problems themselves through the Exploratory Action Research (EAR) process is therefore the right answer. Furthermore, it truly aligns with the Teacher and Educational Personnel (TEP) professional evaluation and development criteria.',
    journey_year_1_2_title: 'Year 1 (2022)',
    journey_phase_1_2: 'Igniting the Spark and Laying the Foundation',
    journey_desc_2_1: 'The project started with training 21 English teachers. The School of Liberal Arts, KMUTT organized the training process using the Exploratory Action Research (EAR) training model, which was developed by Professor Dr. Richard Smith from the University of Warwick and Dr. Paula Rebolledo, and has been successful in many countries since 2018.',
    journey_desc_2_2: 'The training, conducted before the start of the first semester, focused on providing knowledge about the research process. Then, throughout the first semester, teachers conducted actual research while receiving close consultation from British Council experts and international mentor teachers. Having mentors to support them like this is the heart of helping teachers complete their research, aligning with the perspective of Dr. Suwimon Wongwanich, who reflected on the challenges:',
    journey_quote: '"The various processes used in conducting research are unfamiliar to teachers, difficult to understand, and require consistent practice under the guidance of mentors who understand research methodologies. However, in reality, after training, teachers conducting research lack helping mentors, genuine experience, and expertise, resulting in flawed research reports."',
    journey_quote_author: 'Dr. Suwimon Wongwanich',
    journey_desc_2_3: 'As a result of completing the research process, teachers reflected on positive changes, including better attitudes towards conducting research, stronger relationships between teachers and students, and the ability to solve classroom problems accurately using empirical evidence instead of guesswork (Dersingh & Vuong, 2023). These concrete successes made the British Council and KMUTT confident in the project\'s value and ready to move forward with planning to expand operations in the next phase.',
    journey_year_2_4_title: 'Years 2 - 4 (2023 - 2025)',
    journey_phase_2_4: 'Cultivating Core Leaders and Preparing for the Network',
    journey_desc_3_1: 'Because using foreign mentor teachers incurs high costs, the project recognized the need for long-term sustainability. In Year 2 (2023), teachers with potential from the first cohort were selected to be developed as "Teacher-Research Mentors", with the honor of having British expert Professor Dr. Richard Smith impart his knowledge.',
    journey_desc_3_2: 'Over these three years, the mentors have provided consultation to fellow teachers, enabling the project to expand its training to cover 40 provinces nationwide. This allowed members and mentors to be thoroughly distributed across various regions, leading up to the preparation for a significant elevation of cooperation.',
    journey_year_5_6_title: 'Years 5 - 6 (2026 - 2028)',
    journey_phase_5_6: 'The Birth of the TReN Network and National Mobilization',
    journey_desc_4_1: 'The growth of teacher-researcher groups nationwide led to the official establishment of the "Teacher-Research Network (TReN)".',
    journey_bullet_4_1_strong: 'Elevating Area-Based Networks:',
    journey_bullet_4_1_desc: 'Expanding outcomes through regional Communities of Practice (Regional CoP - EARC), divided into 8 zones nationwide (Central, Upper-Lower North, Upper-Lower Northeast, East, and Upper-Lower South).',
    journey_bullet_4_2_strong: 'Developing Mentor Potential:',
    journey_bullet_4_2_desc: 'Reaching an Advanced Level in leadership and management so that each region can be self-reliant, with the central TReN providing ongoing support.',
    journey_future_title: '2028 Onwards',
    journey_phase_future: 'Expanding Outcomes for National Sustainability',
    journey_desc_5_1: 'Expanding the EAR research process to teachers nationwide through the TReN network, while conducting an Impact Analysis to concretely measure the changes that occur in teachers, classrooms, students, and communities.',
  
    journey_intro_desc_new: 'From the Beginning to a National Research Network (2022 - Present)',
    
    // Phase 1: The Origin (2022)
    journey_year_1_title_new: '2022',
    journey_phase_1_new: 'The Origin',
    journey_tren_brand: 'TReN',
    journey_desc_1_1_new: 'Originated from the collaboration between British Council Thailand and the School of Liberal Arts, King Mongkut\'s University of Technology Thonburi (KMUTT), aimed at equipping in-service teachers with the ability to analyze and solve classroom problems on their own. Because the context of each classroom is different, waiting for external assistance or making problem-solving decisions based on personal feelings is unsustainable.',
    journey_key_takeaway_new: 'Evidence-based decision',
    journey_desc_1_2_new: 'The project therefore promotes the principle of making decisions based on evidence through the Exploratory Action Research (EAR) process, so that teachers can solve problems precisely and in accordance with the professional development criteria of the OTEPC.',

    // Phase 2: Year 1 (2022)
    journey_year_2_title_new: 'Year 1: 2022',
    journey_phase_2_new: 'Igniting and Laying the Foundation',
    journey_desc_2_1_new: 'Bringing the global EAR research model of Prof. Dr. Richard Smith (University of Warwick) and Dr. Paula Rebolledo to train the first cohort of 21 English teachers, with international experts and mentors providing close supervision. Having these supporting mentors is considered the heart of success, as Dr. Suwimon Wongwanich interestingly reflected:',
    journey_quote_new: '"The various processes used in conducting research are unfamiliar to teachers, difficult to understand, and require practice under the guidance of mentors who consistently understand research methodologies..."',
    journey_quote_author_new: '— (Suwimon Wongwanich, 2007, p. 6)',
    journey_desc_2_2_new: 'Upon completing the project, teachers not only had a better attitude towards conducting research, but they were also able to solve classroom problems directly, while building stronger relationships with their students (Dersingh & Vuong, 2023).',

    // Phase 3: Year 2 - 4 (2023 – 2025)
    journey_year_3_title_new: 'Year 2 – 4: 2023 – 2025',
    journey_phase_3_new: 'Incubating Leaders to 40 Provinces',
    journey_desc_3_1_new: 'To build sustainability and reduce reliance on foreign experts, the project selected teachers from the first cohort to be further developed into ',
    journey_mentor_role: '"Teacher-Research Mentors"',
    journey_desc_3_2_new: ' and was honored by Prof. Dr. Richard Smith who directly transferred the body of knowledge, until this group of core mentors could expand their results by providing consultation to fellow teachers, covering up to 40 provinces nationwide.',

    // Phase 4: Year 5 - 6 (2026 Onwards)
    journey_year_4_title_new: 'Year 5 - 6 Onwards: 2026 Onwards',
    journey_phase_4_new: 'Founding TReN and Expanding Nationwide',
    journey_desc_4_1_new: 'The strength of the group of research teachers and mentors nationwide led to the founding of ',
    journey_tren_network: 'the TReN (Teacher-Research Network)',
    journey_desc_4_2_new: ' officially, driven through regional Communities of Practice (EART Communities: EARC) divided into 8 zones nationwide, alongside elevating mentors to the Advanced Level so that each area can be self-reliant in the long term. This is accompanied by an aim to expand the EAR process to teachers nationwide and assess the in-depth impact sustainably.',

    // Summary of Growth Figures (Table)
    journey_table_main_title: 'Summary of the Network\'s Growth Figures',
    journey_table_col1: 'Indicator',
    journey_table_col1_en: '(Key Indicator)',
    journey_table_col2: 'Success Figures',
    journey_table_col3: 'Expansion Details',

    // Table Stats
    journey_stat_1_name: 'Developed In-service Teachers',
    journey_stat_1_val: '280 Teachers',
    journey_stat_1_desc: 'From the pilot cohort of 21 teachers to solving classroom problems with EAR nationwide',

    journey_stat_2_name: 'Research Mentors',
    journey_stat_2_en: '(Mentors)',
    journey_stat_2_val: '50 Mentors',
    journey_stat_2_desc: 'Incubated from the first cohort of core teachers to experts who continually support fellow teachers',

    journey_stat_3_name: 'Working Areas',
    journey_stat_3_val: '40 Provinces',
    journey_stat_3_desc: 'Distributing learning and care networks thoroughly across all regions',

    journey_stat_4_name: 'Communities of Practice',
    journey_stat_4_en: '(EARCs)',
    journey_stat_4_val: '8 Zones',
    journey_stat_4_desc: 'Elevating area-based networks to be sustainably self-reliant',

    // Table References
    journey_ref_author: '* Suwimon Wongwanich. (2007).',
    journey_ref_book: 'Classroom Action Research',
    journey_ref_pub: '(Xth Edition). Chulalongkorn University Press.',

    // Core Role & Missions Page //
    role_main_title: 'Core Roles and Missions',
    role_subtitle: 'TReN Core Roles & Missions',
    role_intro_headline: 'Core Supporting Body',
    role_intro_headline_en: '(Supporting Body)',
    role_intro_p1: 'TReN serves as a Supporting Body to create genuine sustainability for the teacher development system. It focuses on promoting and supporting Thai teachers to be able to analyze and solve classroom problems on their own through the Exploratory Action Research (EAR) process.',
    role_intro_p2: 'TReN considers the local EAR Community (EARC) as its core and steps in to manage sustainability by promoting, supporting, and strengthening the EARC in each region so they can manage themselves, continuously develop members\' potential in conducting EAR research, and expand the training to cover teachers nationwide in a self-reliant manner in the long term.',
    role_intro_bridge: 'By driving the missions through 3 main pillars:',
    role_pillar_prefix: 'Pillar',

    role_pillar_1_title: 'Capacity Building and Academic Elevation',
    role_pillar_1_en: '(Capacity Building & Mentor Training)',
    role_p1_item1_name: 'National Classroom Research Training (Centralized EAR Workshop)',
    role_p1_item1_desc: 'Organize centralized training 1–2 times a year to create standards for Exploratory Action Research (EAR) and expand opportunities for teachers in remote areas to access the self-development process.',
    role_p1_item2_name: 'Advanced Mentor Potential Development (Mentor Advanced Training)',
    role_p1_item2_desc: 'Organize workshops to provide advanced skills (such as Co-coaching and Advanced Reflective Practice) to the existing group of mentors, along with cultivating a new generation of mentors to support the expansion of the network.',
    role_p1_item3_name: 'Online Academic Seminars (TReN Webinar Series)',
    role_p1_item3_desc: 'Continuously organize online seminars to develop new bodies of knowledge by inviting experts from higher education institutions, the British Council, and RELO to share trends in modern learning management.',

    role_pillar_2_title: 'Network Management and Monitoring and Evaluation',
    role_pillar_2_en: '(Governance & Network Management)',
    role_p2_item1_name: 'National Network Follow-up and Strategy Meeting (Annual EARC Review & Strategy Meeting / TReN Retreat)',
    role_p2_item1_desc: 'A platform for EARC representatives to report on operational results, exchange challenges, and receive new skills fulfillment (Retraining) to bring back and drive their own areas strongly and self-reliantly.',
    role_p2_item2_name: 'In-depth Monitoring and Evaluation (Impact Analysis)',
    role_p2_item2_desc: 'Concretely evaluate and monitor the impacts of conducting EAR research, in the dimensions of changes in teachers, classrooms, students, and communities, in order to use the data to improve long-term educational development strategies.',
  
    role_pillar_3_title: 'Work Dissemination and International Connection',
    role_pillar_3_en: '(Dissemination, Impact Analysis & Internationalization)',
    role_p3_item1_name: 'National and Regional Academic Conferences (EAR Conference)',
    role_p3_item1_desc: 'Organize platforms for presenting classroom research work (both in Oral and Poster Presentation formats) to promote professional advancement and create pride for teachers in the network.',
    role_p3_item2_name: 'Regional Action Research Exchange Project (Cross-Border AR Fellowship Program)',
    role_p3_item2_desc: 'Join forces with the British Council and RELO in expanding the EAR process to neighboring countries (Laos, Cambodia, Vietnam, and Myanmar), while pushing Thai mentors to become experts and provide consultation at the regional level.',
  
    // Governance & Charter Page //
    governance_main_title: 'Governance Framework',
    governance_subtitle: 'Governance & Charter',
    governance_doc_title: 'Network Charter (TReN Charter)',
    governance_doc_desc: 'A document defining the working framework of the TReN network to create mutual understanding and build sustainability in operations.',
    governance_btn_download: 'Download Document',

    // Supporter Page //
    sponsor_british_council: 'British Council Thailand',
    sponsor_relo: 'Regional English Language Office (RELO), U.S. Embassy in Thailand',
    sponsor_kmutt: 'King Mongkut\'s University of Technology Thonburi (KMUTT)',
    sponsor_earc: 'Community of Practice Network (EAR Community - EARC)',
    sponsor_obec: 'Bureau of Academic Affairs and Educational Standards, Office of the Basic Education Commission (OBEC), Ministry of Education',
    sponsor_ptt: 'PTT Public Company Limited',
    sponsor_eef: 'Equitable Education Fund (EEF)',
    sponsor_earc_desc: 'A network of classroom teacher-researchers formed by the gathering of teachers participating in the TReN project in each region to exchange learning and support one another.',
    
    sponsors_main_title: 'Partner Organizations and Sponsors',
    sponsors_subtitle: 'Our Partners & Sponsors',
    sponsors_intro: 'The success and sustainable growth of the TReN network are made possible by the vision and invaluable support from partners in all sectors, who join forces to develop the potential of Thai teachers and continuously elevate the quality of education.',
    sponsors_thank_you: 'The TReN network would like to express our deepest gratitude to all our partner organizations:',
    sponsors_outro: 'Every form of support is a vital force in driving Thai teachers to become leaders of change, in order to pass on quality learning to students nationwide.',

  }
};

type Language = 'th' | 'en';

// 🟢 กำหนด Type ให้ Context ยืดหยุ่นขึ้น (รับค่าเป็น any หรือ string ได้)
interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: any) => string; 
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  // ดึงภาษาเดิมที่เคยเลือกไว้ ถ้าไม่มีให้เริ่มที่ 'th'
  const [language, setLanguageState] = useState<Language>(
    (localStorage.getItem('app_language') as Language) || 'th'
  );

  // ฟังก์ชันเปลี่ยนภาษาและบันทึกลง Local Storage
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  // 🟢 ฟังก์ชัน t (Translate) ปรับให้อนุโลมการรับค่า
  const t = (key: any) => {
    const dict = translations[language] as Record<string, string>;
    return dict[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};