// src/contexts/LanguageContext.tsx
/* eslint-disable react-refresh/only-export-components */
import { createContext, useState, useContext, type ReactNode } from 'react';

// 1. สร้าง Dictionary เก็บคำแปลทั้งหมดในเว็บ
const translations = {
  th: {
    // Login Modal
    login_tab: 'เข้าสู่ระบบ',
    register_tab: 'สมัครสมาชิก',
    password: 'รหัสผ่าน',
    remember_me: 'จดจำฉันไว้',
    forgot_password: 'ลืมรหัสผ่าน?',
    school_province_placeholder: 'จังหวัดของโรงเรียน',
    teacher_rank_placeholder: 'วิทยฐานะของคุณครู',
    processing: 'กำลังดำเนินการ...',
    login_success: 'เข้าสู่ระบบสำเร็จ!',
    account_suspended: 'บัญชีของคุณถูกระงับการใช้งาน',
    unknown_error: 'เกิดข้อผิดพลาดที่ไม่รู้จัก',
    register_success: 'สมัครสมาชิกสำเร็จ!',

    // Footer
    copyright: 'ลิขสิทธิ์ © 2026 - TReN.org',
    languageLabel: 'ภาษาที่ใช้ :',

    // Navbar 
    home: 'หน้าหลัก',
    events: 'กิจกรรม',
    blogs: 'บล็อกบทความ',
    resources: 'คลังความรู้',
    showcases: 'ผลงานเด่น',
    about: 'เกี่ยวกับเรา',

    // Password Update Page //
    back_to_home: 'กลับสู่หน้าหลัก',
    update_password_title: 'ตั้งรหัสผ่านใหม่',
    update_password_desc: 'กรุณากำหนดรหัสผ่านใหม่ของคุณเพื่อเข้าสู่ระบบ',
    new_password: 'รหัสผ่านใหม่',
    confirm_new_password: 'ยืนยันรหัสผ่านใหม่',
    confirm_password_placeholder: 'กรอกรหัสผ่านใหม่อีกครั้ง',
    invalid_reset_link: 'ลิงก์รีเซ็ตรหัสผ่านไม่ถูกต้องหรือหมดอายุ',
    password_min_length: 'รหัสผ่านต้องมีความยาวอย่างน้อย 6 ตัวอักษร',
    password_mismatch: 'รหัสผ่านใหม่และการยืนยันรหัสผ่านไม่ตรงกัน',
    password_update_success: 'อัปเดตรหัสผ่านสำเร็จ! คุณสามารถเข้าสู่ระบบด้วยรหัสผ่านใหม่ของคุณได้แล้ว',
    password_update_error: 'เกิดข้อผิดพลาดในการอัปเดตรหัสผ่าน กรุณาลองใหม่อีกครั้ง',
    password_min_length_hint: 'อย่างน้อย 6 ตัวอักษร',
    error_same_password: 'กรุณาเลือกใช้รหัสผ่านใหม่ที่แตกต่างจากรหัสผ่านเก่าของคุณ',
    error_weak_password: 'รหัสผ่านอ่อนแอเกินไป กรุณาเลือกรหัสผ่านที่แข็งแรงกว่านี้',

    // Navbar Dropdown 
    profile: 'โปรไฟล์',
    adminDashboard: 'แดชบอร์ดแอดมิน',
    logout: 'ออกจากระบบ',
    upcoming_events_navbar: 'กิจกรรมที่กำลังจะถึง',
    past_events_navbar: 'กิจกรรมที่ผ่านมา',
    history_about_us: 'ประวัติความเป็นมา',
    timeline_about_us: 'ไทมไลน์ TReN',

    history_of_ear_about_us: 'ประวัติ EAR',
    organization_about_us: 'องค์กรของเรา',
    mission_about_us: 'ภารกิจของเรา',
    what_is_tren_about_us: 'TReN คืออะไร',
    history_of_tren_about_us: 'ประวัติ TReN',
    ear_team_about_us: 'ทีม EAR',
    constitution_about_us: 'รัฐธรรมนูญ',
    supporter_about_us: 'ผู้สนับสนุน',


    // Profile Page
    profile_title: 'โปรไฟล์ของฉัน',
    edit_profile: 'แก้ไขโปรไฟล์',
    published: 'เผยแพร่',
    in_progress: 'อยู่ในระหว่างดำเนินการ',
    edit: 'แก้ไข',
    no_contents_desc: 'ยังไม่มีเนื้อหาที่สร้างขึ้น',
    no_pending_contents_desc: 'ไม่มีเนื้อหาที่รอดำเนินการในขณะนี้',
    loading_profile: 'กำลังโหลดโปรไฟล์...',

    edit_profile_save: 'บันทึกการเปลี่ยนแปลง',
    edit_profile_saving: 'กำลังบันทึก...',
    edit_profile_cancel: 'ยกเลิก',
    save_success: 'บันทึกสำเร็จ!',
    save_error: 'เกิดข้อผิดพลาดในการบันทึก',
    edit_profile_title: 'แก้ไขโปรไฟล์',
    edit_profile_change_photo: 'เปลี่ยนรูปโปรไฟล์',
    first_name: 'ชื่อ',
    last_name: 'นามสกุล',
    select_province: 'เลือกจังหวัด',
    select_position: 'เลือกตำแหน่ง',
    select_rank: 'เลือกตำแหน่งทางวิชาการ',
    teacher: 'ครู',
    assistant_teacher: 'ผู้ช่วยครู',
    cannot_change_email: 'ไม่สามารถเปลี่ยนอีเมลได้',
    password_label: 'รหัสผ่านใหม่ (เว้นว่างหากไม่ต้องการเปลี่ยน)',
    bio: 'ประวัติส่วนตัว',

    status_rejected: 'ปฏิเสธ',
    delete: 'ลบ',
    view_rejection_reason: 'ดูเหตุผล',
    rejection_reason: 'เหตุผลที่ถูกปฏิเสธ',
    close: 'ปิด',
    deleting: 'กำลังลบ...',
    confirm_delete: 'ยืนยันการลบข้อมูล',
    are_you_sure_you_want_to_delete: 'คุณแน่ใจหรือไม่ที่จะลบ',
    this_action_cannot_be_undone: 'การกระทำนี้ไม่สามารถย้อนกลับได้',

    create_blog: 'สร้างบล็อก',
    create_event: 'สร้างกิจกรรม',
    create_showcase: 'สร้างผลงานเด่น',
    delete_success: 'ลบข้อมูลเรียบร้อยแล้ว',

    // Create Event Page
    create_event_title: 'สร้างกิจกรรมใหม่',
    create_event_desc: 'สร้างนัดหมายกิจกรรมเพื่อให้ผู้คนเข้าร่วม',
    creat_event_name: 'ชื่อกิจกรรม',
    event_date: 'วันที่',
    event_time: 'เวลา',
    event_location: 'สถานที่',   
    event_brief_description: 'รายละเอียดกิจกรรมโดยย่อ',
    add_image_cover: 'เพิ่มรูปภาพปกกิจกรรม',
    post_event_details: 'เพิ่มรายละเอียดหลังเสร็จกิจกรรม',
    about_event: 'เกี่ยวกับกิจกรรม',
    conclude_info: 'สรุปข้อมูลกิจกรรมหลังจบงานกิจกรรม',
    resource_link: 'ลิงก์รวมรวบข้อมูล',
    up_to_links: 'อัปโหลดได้สูงสุด 2 ลิงก์',
    event_creating: 'กำลังสร้าง...',
    event_submit_btn: 'สร้างกิจกรรม',
    attach_media: 'แนบสื่อ',
    create_event_success: 'สร้างกิจกรรมสำเร็จ!',
    create_event_error: 'เกิดข้อผิดพลาดในการสร้างกิจกรรม',

    update_event_success: 'อัปเดตกิจกรรมสำเร็จ!',
    update_event_error: 'เกิดข้อผิดพลาดในการอัปเดตกิจกรรม',
    edit_event_title: 'แก้ไขกิจกรรม',
    event_save_changes: 'บันทึกการเปลี่ยนแปลง',

    file_size_exceeded: 'ขนาดไฟล์เกิน 5MB',
    invalid_file_type: 'ประเภทไฟล์ไม่ถูกต้อง (รองรับเฉพาะ .jpg, .jpeg, .png)',
    edit_event_success_pending: 'บันทึกการเปลี่ยนแปลงเรียบร้อยแล้ว! โปรดรอการตรวจสอบจากทีมงาน',
    edit_event_success: 'บันทึกการเปลี่ยนแปลงเรียบร้อยแล้ว!',

    add_link: 'เพิ่มลิงก์',
    no_permission: 'คุณไม่มีสิทธิ์เข้าถึงหน้านี้',

    // Comment Section
    share_comments: 'แชร์ความคิดเห็นของคุณ',
    no_comments_yet: 'ยังไม่มีความคิดเห็น เป็นคนแรกที่คอมเมนต์สิ!',
    leave_a_reply: 'แสดงความคิดเห็น',
    write_a_comment: 'เขียนความคิดเห็นของคุณที่นี่...',
    post_comment: 'โพสต์ความคิดเห็น',
    must_log_in_to_comment: 'คุณต้องเข้าสู่ระบบก่อนจึงจะสามารถคอมเมนต์ได้',
    post: 'โพสต์',
    reply: 'ตอบกลับ',
    comment_delete: 'ลบความคิดเห็น',
    view_replies: 'ดูคำตอบ',
    confirm_delete_comment: 'คุณต้องการลบคอมเมนต์นี้ใช่หรือไม่?',
    are_you_sure_you_want_to_delete_comment: 'การลบจะลบการตอบกลับย่อยทั้งหมดด้วย',
    delete_comment_warning: 'การกระทำนี้ไม่สามารถย้อนกลับได้',

    // Blog Detail Page
    success: 'สำเร็จ',
    error: 'เกิดข้อผิดพลาด',
    ok: 'ตกลง',
    no_permission_blog: 'คุณไม่มีสิทธิ์เข้าถึงเนื้อหานี้',
    link_copied: 'คัดลอกลิงก์แล้ว!',
    preview_warning: 'คุณกำลังดูตัวอย่าง (Preview) | สถานะปัจจุบัน:',
    status_in_progress: 'แบบร่าง (In Progress)',
    share_post: 'แชร์โพสต์นี้',
    no_bio: 'ผู้เขียนยังไม่ได้เพิ่มคำอธิบายตัวเอง (Bio)',
    more_posts: 'ดูเพิ่มเติม',
    related_blogs: 'บล็อกที่เกี่ยวข้อง',
    view_all: 'ดูทั้งหมด',
    by_author: 'โดย',
    read_more: 'อ่านเพิ่มเติม',
    loading_blogs: 'กำลังโหลดบล็อก...',
    blog_not_found: 'ไม่พบบล็อกบทความ',

    // Create Blog Page
    msg_edit_pending: 'ส่งข้อมูลที่แก้ไขเพื่อรอตรวจสอบเรียบร้อยแล้ว!',
    msg_edit_success: 'แก้ไขบล็อกสำเร็จแล้ว!',
    msg_create_success: 'สร้างบล็อกสำเร็จแล้ว!',
    msg_edit_draft: 'อัปเดตแบบร่างสำเร็จ!',
    msg_edit_published: 'บันทึกเรียบร้อย',

    msg_create_pending: 'ส่งบล็อกใหม่เพื่อรอตรวจสอบเรียบร้อยแล้ว!',
    msg_create_error: 'เกิดข้อผิดพลาดในการสร้างบล็อก',
    msg_edit_error: 'เกิดข้อผิดพลาดในการแก้ไขบล็อก',
    msg_create_draft: 'สร้างแบบร่างสำเร็จ!',
    msg_create_published: 'เผยแพร่บล็อกสำเร็จ!',

    loading_blogs_editor: 'กำลังโหลดบล็อก...',
    enter_blog_title: 'กรอกชื่อบล็อกของคุณ...',
    start_writing: 'เริ่มเขียนเนื้อหาของคุณที่นี่...',
    back_to_dashboard: 'กลับไปที่แดชบอร์ด',
    save_changes: 'บันทึกการเปลี่ยนแปลง',
    publish: 'เผยแพร่',
    save_draft: 'บันทึกแบบร่าง',
    click_change_image: 'กดเพื่อเปลี่ยนรูปภาพ',
    add_blog_cover: 'เพิ่มรูปหน้าปกบล็อกที่นี่.',
    press_enterToAddTag: 'กดปุ่ม Enter หรือกดปุ่ม "เพิ่ม" เพื่อสร้างแท็ก',
    category_and_tags: 'หมวดหมู่และแท็ก',
    add_tag: 'เพิ่มแท็ก',
    delete_tag: 'ลบแท็ก',
    add_tags: 'เพิ่มแท็ก...',
    add_more_tags: 'เพิ่มแท็กเพิ่มเติม...',

    as_new_tag: 'เป็นแท็กใหม่: ',
    tag_input_hint: '* ค้นหาแท็กที่เคยใช้ หรือพิมพ์แท็กใหม่แล้วกด Enter เพื่อเพิ่ม',
    link_title: 'ลิงก์แหล่งที่มา, URL สไลด์, หรือ URL YouTube/Vimeo',

    // All Blogs Page
    teacher_blogs: 'บล็อกของคุณครู',
    all_teachers_blogs: 'บล็อกของคุณครู',
    search_explore_blogs: 'ค้นหาและสำรวจบล็อกทั้งหมดได้ที่นี่',
    search_blogs_placeholder: 'ค้นหาโดยชื่อผู้เขียน บล็อก หรือ แท็ก..',
    next: 'ถัดไป',
    no_blogs_found: 'ไม่พบบล็อก',
    no_blogs_found_desc: 'ไม่พบบทความที่ตรงกับการค้นหา หรือในหมวดหมู่นี้',
    all: 'ทั้งหมด',
    no_image: 'ไม่มีรูปภาพ',
    tag_research: 'งานวิจัย',
    tag_tips: 'เคล็ดลับ',
    tag_teaching: 'การสอน',
    tag_innovation: 'นวัตกรรม',
    tag_other: 'อื่นๆ',

    // All Events Page
    all_events: 'กิจกรรมทั้งหมด',
    search_explore_events: 'ค้นหาและสำรวจกิจกรรมทั้งหมดได้ที่นี่',
    search_events_placeholder: 'ค้นหาโดยชื่อกิจกรรมหรือคีย์เวิร์ด..',
    previous: 'ก่อนหน้า',
    no_events_found: 'ไม่พบกิจกรรม',
    no_events_found_desc: 'ไม่พบกิจกรรมที่ตรงกับการค้นหา หรือในหมวดหมู่นี้',
    all_event_date: 'วันที่',
    all_event_time: 'เวลา',
    all_event_place: 'สถานที่',
    all_event_no_brief_description: 'ไม่มีคำอธิบายโดยย่อ',
    
    filter_all: 'ทั้งหมด',
    filter_upcoming: 'กำลังจะมาถึง',
    filter_past: 'ผ่านไปแล้ว',
    filter_done: 'เสร็จสิ้น',

    // All Showcases Page
    showcases_menu: 'ผลงานทั้งหมด',
    all_showcases_title: 'ผลงานทั้งหมด',
    search_explore_showcases: 'ค้นหาและสำรวจผลงานทั้งหมดได้ที่นี่',
    search_showcases_placeholder: 'ค้นหาโดยชื่อผลงาน ผู้สร้าง หรือ คีย์เวิร์ด..',
    no_showcases_found: 'ไม่พบผลงาน',
    no_showcases_found_desc: 'ไม่พบผลงานที่ตรงกับการค้นหา หรือในหมวดหมู่นี้',
    explore_showcases_desc: 'สำรวจและค้นพบผลงานที่สร้างโดยคุณครูเพื่อเป็นแรงบันดาลใจสำหรับผลงานของคุณเอง!',
    tag_article: 'บทความ',
    tag_presentation: 'การนำเสนอ',

    
    // Create Showcase Page
    require_title: 'กรุณากรอกชื่อผลงาน',
    require_login: 'คุณต้องเข้าสู่ระบบก่อนจึงจะสามารถสร้างผลงานได้',
    require_description: 'กรุณากรอกคำอธิบาย',
    create_showcase_success: 'สร้างผลงานสำเร็จ!',
    edit_showcase_pending: 'บันทึกการเปลี่ยนแปลงแล้ว!',
    edit_showcase_success: 'อัปเดตผลงานสำเร็จ!',
    edit_showcase_published: 'บันทึกเรียบร้อย',
    create_showcase_published: 'เผยแพร่ผลงานสำเร็จ!',
    create_showcase_pending: 'ส่งผลงานของคุณเรียบร้อยแล้ว',
    error_saving: 'เกิดข้อผิดพลาดขณะบันทึกผลงาน',
    create_showcase_error: 'เกิดข้อผิดพลาดขณะสร้างผลงาน',
    edit_showcase_error: 'เกิดข้อผิดพลาดขณะแก้ไขผลงาน',
    create_showcase_title: 'สร้างผลงานเด่น',
    edit_showcase_title: 'แก้ไขผลงาน',
    save_showcase_changes: 'บันทึกการเปลี่ยนแปลง',
    create_showcase_desc: 'แบ่งปันผลงานของคุณกับครูท่านอื่น ๆ',
    create_showcase_title_name: 'ชื่อผลงาน',
    create_showcase_author: 'ผู้สร้าง',
    create_showcase_description: 'คำอธิบาย',
    create_showcase_add_image: 'เพิ่มรูปหน้าปก',
    link_to_work: 'ลิงก์ไปยังผลงานของคุณ',
    create_showcase_image_desc: 'คุณสามารถเพิ่มรูปภาพเพื่อแสดงผลงานของคุณ (ไม่จำเป็น)',
    showcase_brief_description: 'คำอธิบายโดยย่อ',
    change_media: 'เปลี่ยนไฟล์สื่อ',
    create_showcase_btn: 'สร้างผลงาน',
    published_date: 'วันที่เผยแพร่',
    visit_work: 'ไปยังหน้าผลงาน',
    create_showcase_author_hint: 'ค้นหาชื่อครูในระบบ หรือพิมพ์ชื่อเองแล้วกด Enter เพื่อเพิ่ม',
    searching: 'กำลังค้นหา...',
    add: 'เพิ่ม',
    no_links_provided: 'ไม่มีลิงก์ที่มาสำหรับผลงานนี้',

    // Admin Dashboard Sidebar
    menu: 'รายการทั้งหมด',
    admin_menu: 'รายการทั้งหมด',
    overview: 'ภาพรวม',
    blog: 'บล็อกบทความ',
    event: 'กิจกรรม',
    showcase: 'ผลงานเด่น',
    resource: 'คลังความรู้',
    reports: 'รายงาน',
    users: 'ผู้ใช้งาน',
    search: 'ค้นหา...',
    status: 'สถานะ',

    // Admin Dashboard Table
    type: 'ประเภท',
    titleSubject: 'ชื่อ/หัวข้อ',
    submittedBy: 'สร้างโดย',
    date: 'ณ วันที่',
    view: 'รายละเอียด',
    action: 'การดำเนินการ',

    // Admin Dashboard Overview
    dashboard: 'ภาพรวมแดชบอร์ด',
    pendingRequests: 'คำขอที่รอดำเนินการ',
    reports_overall: 'รายงาน',
    totalUsers: 'ผู้ใช้งานทั้งหมด',
    recentPendingRequests: 'คำขอที่รอดำเนินการล่าสุด',
    only_admin_can_perform_this_action: 'เฉพาะผู้ดูแลระบบ',
    type_report: 'รายงานทั่วไป',
    type_blog: 'บล็อกบทความ',
    type_event: 'กิจกรรม',
    type_showcase: 'ผลงาน',
    loading: 'กำลังโหลด...',
    showing: 'แสดง',
    to: 'ถึง',
    from: 'จาก',
    list: 'รายการ',
    page: 'หน้า',

    // Admin Blogs
    blog_title: 'บล็อกบทความ',
    no_blogs: 'ไม่พบบล็อกบทความ',
    reject_blog_title: 'ปฏิเสธเนื้อหาบล็อก',
    reject_blog_reason: 'กรุณาระบุเหตุผล:',
    reject_blog_placeholder: 'เช่น เนื้อหาไม่เหมาะสม, ละเมิดลิขสิทธิ์ เป็นต้น...',
    confirm_reject: 'ยืนยัน',
    delete_blog_success: 'ลบบล็อกเรียบร้อยแล้ว',

    // Admin Events
    event_title: 'กิจกรรม',
    no_events: 'ไม่พบกิจกรรม',
    event_actions: 'การดำเนินการ',
    done: 'เสร็จสิ้นกิจกรรม',
    event_status: 'สถานะกิจกรรม',
    publish_state: 'การอนุมัติ',
    status_upcoming: 'กำลังมาถึง',
    status_past: 'ผ่านไปแล้ว',
    status_done: 'เสร็จสิ้น',
    state_pending: 'รอตรวจสอบ',
    state_published: 'เผยแพร่แล้ว',
    state_rejected: 'ไม่อนุมัติ',
    create_date: 'วันที่สร้าง',
    admin_events_confirm_approve: 'คุณแน่ใจหรือไม่ว่าต้องการอนุมัติกิจกรรมนี้?',
    admin_events_confirm_mark_as_done: 'คุณแน่ใจหรือไม่ว่าต้องการเปลี่ยนสถานะกิจกรรมนี้เป็น "เสร็จสิ้น" ?',
    admin_events_mark_as_done_success: 'กิจกรรมถูกทำเครื่องหมายว่าเสร็จสิ้นเรียบร้อยแล้ว',
    admin_events_approve_success: 'อนุมัติกิจกรรมให้เผยแพร่เรียบร้อยแล้ว',
    error_updating_event_occurred: 'เกิดข้อผิดพลาดในการอัปเดตกิจกรรม',
    confirm: 'ตกลง',
    cancel: 'ยกเลิก',
    loading_events: 'กำลังโหลดกิจกรรม...',
    view_event_details: 'ดูรายละเอียดกิจกรรม',
    approve: 'อนุมัติ',
    delete_event_success: 'ลบกิจกรรมเรียบร้อยแล้ว',

    // Admin Showcases
    showcase_title: 'ผลงานเด่น',
    no_showcases: 'ไม่พบผลงานเด่น',
    loading_showcases: 'กำลังโหลดผลงาน...',

    // Admin Reports
    report_title: 'รายงาน',
    no_reports: 'ไม่พบรายงาน',
    loading_reports: 'กำลังโหลดรายงาน...',
    resolved: 'ดำเนินการแล้ว',
    ticket_inquiry: 'สอบถามข้อมูล',
    ticket_bug: 'ปัญหาการใช้งาน',
    ticket_comment: 'รายงานทั่วไป',

    report_desc: 'รายละเอียด',
    reporter: 'ผู้รายงาน',
    report_date: 'วันที่รายงาน',
    admin_note: 'บันทึกการดำเนินการ',
    view_source: 'ไปยังแหล่งที่มา',
    report_category: 'หมวดหมู่การรายงาน',

    confirm_resolved: 'แก้ไขปัญหาเรียบร้อย',
    confirm_resolved_message: 'คุณกำลังอัปเดตสถานะของ',
    resolve_modal_placeholder: 'เช่น ทำการลบบล็อกนี้ออกจากระบบแล้ว, ทำการแบนผู้ใช้งานชั่วคราว...',
    save_report_status: 'บันทึกสถานะ',
    confirm_reject_message: 'คุณกำลังปฏิเสธคำร้องเรียน',
    reject_reason: 'เหตุผลในการปฏิเสธ',
    reject_modal_placeholder: 'เช่น ตรวจสอบแล้วไม่พบการละเมิดกฎ, ข้อมูลไม่เพียงพอ...',
    save_rejection: 'บันทึกการปฏิเสธ',
    delete_report_success: 'ลบรายงานเรียบร้อยแล้ว',
    report_pending: 'รอดำเนินการ',

    // Admin Users
    no_users: 'ไม่พบผู้ใช้งาน',
    id: 'รหัสผู้ใช้',
    profile_pic: 'รูปโปรไฟล์',
    name: 'ชื่อ-นามสกุล',
    role: 'ตำแหน่ง',
    joined_date: 'วันที่เข้าร่วม',
    email: 'อีเมล',
    school: 'โรงเรียน',
    province: 'จังหวัด',
    position: 'ตำแหน่ง',
    academic_rank: 'ตำแหน่งทางวิชาการ',
    total_blogs: 'จำนวนบล็อก',
    total_showcases: 'จำนวนผลงาน',
    ban_user: 'ระงับบัญชีผู้ใช้งาน',
    user: 'ผู้ใช้งาน',
    account_details: 'รายละเอียดผู้ใช้งาน',
    post_count: 'โพสต์',
    showcase_count: 'ผลงาน',

    confirm_ban: 'ยืนยันการระงับบัญชี',
    confirm_ban_message: 'คุณกำลังระงับบัญชีผู้ใช้งาน',
    confirm_unban: 'ยืนยันการปลดระงับบัญชี',
    confirm_unban_message: 'คุณกำลังปลดระงับบัญชีผู้ใช้งาน',
    unban_user: 'ปลดระงับบัญชีผู้ใช้',
    are_you_sure_you_want_to_ban: 'คุณแน่ใจหรือไม่ที่จะระงับบัญชีผู้ใช้งาน',
    user_banned_successfully: 'ระงับบัญชีผู้ใช้งานเรียบร้อยแล้ว',
    user_unbanned_successfully: 'ปลดระงับบัญชีผู้ใช้งานเรียบร้อยแล้ว',
    this_user_login_disabled: 'ผู้ใช้นี้จะไม่สามารถล็อกอินเข้าสู่ระบบได้อีกจนกว่าจะถูกปลดแบน',
    are_you_sure_you_want_to_unban: 'คุณแน่ใจหรือไม่ที่จะปลดระงับบัญชีผู้ใช้งาน',
    banned: 'โดนระงับบัญชี',

    // Confirmation Box Approve/Reject
    confirm_approve: 'ยืนยันการอนุมัติ',
    confirm_approve_message: 'คุณแน่ใจหรือไม่ที่จะอนุมัติ',
    content_will_be_published: 'เนื้อหานี้จะถูกเผยแพร่สู่สาธารณะทันที',
    no_pending_requests: 'ไม่มีคำขอที่รอดำเนินการ',
    reject: 'ปฏิเสธ',

    // Report Modal
    report_modal_title: 'รายงานปัญหา',
    report_modal_desc: 'รายงานเนื้อหาที่ไม่เหมาะสมหรือละเมิดกฎ',
    report_modal_category: 'หัวข้อการรายงาน',
    report_category_inappropriate: 'เนื้อหาไม่เหมาะสม / หยาบคาย',
    report_category_copyright_infringement: 'ละเมิดลิขสิทธิ์',
    report_category_spam_ads: 'สแปม / โฆษณาแอบแฝง',
    report_category_false_information: 'ข้อมูลเท็จ / ทำให้เข้าใจผิด',
    report_category_broken_links: 'ลิงก์เสีย / ใช้งานไม่ได้',
    report_category_other: 'อื่นๆ',
    report_modal_description: 'รายละเอียดเพิ่มเติม',
    report_modal_placeholder: 'โปรดอธิบายปัญหาที่คุณพบ...',
    submit_report: 'ส่งรายงาน',
    report_submitted_success: 'รายงานถูกส่งเรียบร้อยแล้ว!',
    report_submitted_error: 'เกิดข้อผิดพลาดขณะส่งรายงาน',
    report_success: 'สำเร็จ',
    report_error: 'เกิดข้อผิดพลาด',

    // Search Page
    find_info_you_need: 'ค้นหาข้อมูลที่คุณต้องการ',
    No_results_found: 'ไม่พบผลลัพธ์สำหรับ',
    try_different_keywords: 'ลองใช้คำค้นหาที่แตกต่างกัน หรือ ลองดูเนื้อหาทั้งหมด',
    found: 'พบ',
    found_for: 'รายการสำหรับ',

    // Resource Page
    all_resources: 'คลังข้อมูลทั้งหมด',
    resources_desc: 'ค้นหาและสำรวจคลังข้อมูลทั้งหมดได้ที่นี่',
    add_resource: 'เพิ่มข้อมูล',
    search_resources: 'ค้นหาโดยชื่อข้อมูลหรือคีย์เวิร์ด..',
    loading_resources: 'กำลังโหลดคลังข้อมูล...',
    no_resources_found: 'ไม่พบข้อมูล',
    no_resources_found_desc: 'ไม่พบคลังข้อมูลที่ตรงกับการค้นหา หรือในหมวดหมู่นี้',
    view_details: 'ดูรายละเอียด',
    resource_title: 'ชื่อข้อมูล',
    resource_category: 'หมวดหมู่',
    try_different_resource_keywords: 'ลองใช้คำค้นหาที่แตกต่างกัน หรือ ลองดูเนื้อหาทั้งหมด',

    filter_document: 'เอกสาร',
    filter_media: 'รูปภาพและวิดีโอ',
    filter_folder: 'แฟ้มข้อมูล',
    filter_link: 'ลิงก์เว็บไซต์',
    resource_edit_success: 'แก้ไขข้อมูลสำเร็จ',
    resource_create_success: 'สร้างข้อมูลสำเร็จ!',
    resource_delete_success: 'ลบข้อมูลเรียบร้อยแล้ว',

    edit_resource_title: 'แก้ไขข้อมูล',
    create_resource_title: 'สร้างข้อมูล',
    create_resource_desc: 'เพิ่มไฟล์ เอกสาร หรือวิดีโอ เพื่อแบ่งปันให้กันและกัน',
    resource_type: 'ประเภทข้อมูล',
    resource_placeholder: 'เช่น วิดีโอสัมมนาวันที่..., เอกสารประกอบการสอน...',
    resource_url: 'ลิงก์ข้อมูล',
    resource_description: 'คำอธิบายข้อมูล',
    resource_description_placeholder: 'คำอธิบายสั้น ๆ เกี่ยวกับข้อมูลนี้...',
    create_resource_button: 'สร้างข้อมูล',
    edit_resource_button: 'บันทึกการเปลี่ยนแปลง',
    resource_file_size_exceeded: 'ขนาดไฟล์เกิน 10MB',
    resource_invalid_file_type: 'ประเภทไฟล์ไม่ถูกต้อง (รองรับเฉพาะ .jpg, .jpeg, .png, .pdf, .mp4)',

    added_on: 'สร้างเมื่อ: ',
    no_description_provided: 'ไม่มีคำอธิบายสำหรับข้อมูลนี้',
    open_folder: 'เปิดโฟลเดอร์',
    view_media: 'ดูสื่อ',
    open_document: 'เปิดเอกสาร',
    open_link: 'เปิดลิงก์',

  },
  en: {
    // Login Modal
    login_tab: 'Log In',
    register_tab: 'Register',
    password: 'Password',
    remember_me: 'Remember me',
    forgot_password: 'Forgot password?',
    school_province_placeholder: 'School Province',
    teacher_rank_placeholder: 'Teacher Academic Rank',
    processing: 'Processing...',
    login_success: 'Login successful!',
    account_suspended: 'Your account has been suspended',
    unknown_error: 'An unknown error occurred',
    register_success: 'Registration successful!',

    // Footer
    copyright: 'Copyright © 2026 - TReN.org',
    languageLabel: 'Language :',

    // Password Update Page //
    back_to_home: 'Back to Home',
    update_password_title: 'Update Password',
    update_password_desc: 'Please set a new password for your account',
    new_password: 'New Password',
    confirm_new_password: 'Confirm New Password',
    confirm_password_placeholder: 'Please enter your new password again',

    invalid_reset_link: 'Invalid or expired password reset link',
    password_min_length: 'Password must be at least 6 characters long',
    password_mismatch: 'New password and confirmation password do not match',
    password_update_success: 'Password updated successfully! You can now log in with your new password.',
    password_update_error: 'An error occurred while updating the password. Please try again.',
    password_min_length_hint: 'At least 6 characters',
    error_same_password: 'New password cannot be the same as the old password',
    error_weak_password: 'Password is too weak. Please choose a stronger password.',

    // Navbar 
    home: 'Home',
    events: 'Events',
    blogs: 'Blogs',
    resources: 'Resources',
    showcases: 'Showcases',
    about: 'About Us',

    // Navbar Dropdown 
    profile: 'Profile',
    adminDashboard: 'Admin Dashboard',
    logout: 'Log out',
    upcoming_events_navbar: 'Upcoming Events',
    past_events_navbar: 'Past Events',
    history_about_us: 'History',
    timeline_about_us: 'TReN Timeline',

    history_of_ear_about_us: 'EAR History',
    organization_about_us: 'Our Organization',
    mission_about_us: 'Our Mission',
    what_is_tren_about_us: 'What is TReN?',
    history_of_tren_about_us: 'History of TReN',
    ear_team_about_us: 'EAR Team',
    constitution_about_us: 'Constitution',
    supporter_about_us: 'Supporters',

    // Profile Page
    profile_title: 'My Profile',
    edit_profile: 'Edit Profile',
    published: 'Published',
    in_progress: 'In Progress',
    edit: 'Edit',
    no_contents_desc: 'No content created yet',
    no_pending_contents_desc: 'No pending content at the moment',
    loading_profile: 'Loading profile...',

    edit_profile_save: 'Save Changes',
    edit_profile_saving: 'Saving...',
    edit_profile_cancel: 'Cancel',
    save_success: 'Changes saved successfully!',
    save_error: 'An error occurred while saving changes',
    edit_profile_title: 'Edit Profile',
    edit_profile_change_photo: 'Change Profile Photo',
    first_name: 'First Name',
    last_name: 'Last Name',
    select_province: 'Select Province',
    select_position: 'Select Position',
    select_rank: 'Select Academic Rank',
    teacher: 'Teacher',
    assistant_teacher: 'Assistant Teacher',
    cannot_change_email: 'Cannot change email',
    password_label: 'New Password (leave blank if not changing)',
    bio: 'Bio',
    view_rejection_reason: 'View Reason',
    delete: 'Delete',
    rejection_reason: 'Rejection Reason',
    close: 'Close',
    status_rejected: 'Rejected',
    deleting: 'Deleting...',
    confirm_delete: 'Confirm Delete',
    are_you_sure_you_want_to_delete: 'Are you sure you want to delete',
    this_action_cannot_be_undone: 'This action cannot be undone',

    create_blog: 'Create Blog',
    create_event: 'Create Event',
    create_showcase: 'Create Showcase',

    delete_success: 'Deleted successfully!',

    // Create Event Page
    create_event_title: 'Create an Event',
    create_event_desc: 'Create an event schedule for people to attend.',
    creat_event_name: 'Event Name',
    event_date: 'Date',
    event_time: 'Time',
    event_location: 'Location',   
    event_brief_description: 'Brief Description',
    add_image_cover: 'Add Image Cover',
    post_event_details: 'Post Event Details',
    about_event: 'About Event',
    conclude_info: 'Conclude Information',
    resource_link: 'Resource Links',
    attach_media: 'Attach Media',
    up_to_links: 'Up to 2 links allowed',
    event_submit_btn: 'Create Event',
    event_creating: 'Creating...',
    create_event_success: 'Create Event Success!',
    create_event_error: 'An error occurred while creating the event',

    update_event_success: 'Update Event Success!',
    update_event_error: 'An error occurred while updating the event',
    edit_event_title: 'Edit Event',
    event_save_changes: 'Save Changes',

    file_size_exceeded: 'File size exceeded (max 5MB)',
    invalid_file_type: 'Invalid file type (only .jpg, .jpeg, .png supported)',
    edit_event_success_pending: 'Changes saved successfully! Please wait for review by the team.',
    edit_event_success: 'Changes saved successfully!',

    add_link: 'Add Link',
    no_permission: 'You do not have permission to access this page',

    // Comment Section
    share_comments: 'Share your comments',
    no_comments_yet: 'No comments yet. Be the first to comment!',
    leave_a_reply: 'leave a reply',
    write_a_comment: 'write a comment here...',
    post_comment: 'Post Comment',
    must_log_in_to_comment: 'You must be logged in to comment',
    post: 'Post',
    reply: 'Reply',
    comment_delete: 'Delete',
    view_replies: 'View Replies',

    confirm_delete_comment: 'Are you sure you want to delete this comment?',
    are_you_sure_you_want_to_delete_comment: 'This delete will delete the comment and all its replies.',
    delete_comment_warning: 'This action cannot be undone',

    // Blog Detail Page
    success: 'success',
    error: 'error',
    ok: 'okay',
    no_permission_blog: 'You do not have permission to access this content',
    link_copied: 'Link copied!',
    preview_warning: 'You are viewing a preview (Preview) | Current Status:',
    status_in_progress: 'Draft (In Progress)',
    share_post: 'Share this post',
    no_bio: 'The author has not added a biography yet (Bio)',
    more_posts: 'View more',
    related_blogs: 'Related Blogs',
    view_all: 'View All',
    by_author: 'By',
    read_more: 'Read More',
    loading_blogs: 'Loading blogs...',
    blog_not_found: 'Blog not found',

    // Create Blog Page
    msg_edit_pending: 'Blog submitted for review!',
    msg_edit_success: 'Successfully edited!',
    msg_create_success: 'Successfully created blog!',
    msg_edit_draft: 'Successfully updated draft!',
    msg_edit_published: 'Successfully saved!',

    msg_create_pending: 'Blog submitted for review!',
    msg_create_error: 'An error occurred while creating the blog',
    msg_edit_error: 'An error occurred while editing the blog',
    msg_create_draft: 'Draft created successfully!',
    msg_create_published: 'Blog published successfully!',

    loading_blogs_editor: 'Loading Editor...',
    enter_blog_title: 'Enter Blog Title...',
    start_writing: 'Start Writing your content here...',
    back_to_dashboard: 'Back to Dashboard',
    save_changes: 'Save Changes',
    publish: 'Publish',
    save_draft: 'Save Draft',
    click_change_image: 'Click to change image',
    add_blog_cover: 'Add blog cover image here.',
    press_enterToAddTag: 'Press Enter or click "Add" to create tag',
    category_and_tags: 'Category & Tags',
    add_tag: 'add tag',
    delete_tag: 'delete tag',
    add_tags: 'Add tags...',
    add_more_tags: 'Add more tags...',

    as_new_tag: 'as a new tag: ',
    tag_input_hint: '* Search for existing tags or type a new tag and press Enter to add',
    link_title: 'Resource link, Slide URL, or YouTube/Vimeo URL',

    // All Blogs Page
    teacher_blogs: 'Teacher\'s Blogs',
    all_teachers_blogs: 'Teacher\'s Blogs',
    search_explore_blogs: 'Search and explore all blogs here',
    search_blogs_placeholder: 'Search by author, blog, or tags...',
    next: 'Next',
    no_blogs_found: 'No blogs found',
    no_blogs_found_desc: 'No articles found that match your search or category',
    all: 'All',
    tag_research: 'Research',
    tag_tips: 'Tips',
    tag_teaching: 'Teaching',
    tag_innovation: 'Innovation',
    tag_other: 'Other',
    no_image: 'No image',

    // Create Showcase Page
    require_title: 'Please fill the title',
    require_login: 'You must be logged in to create a showcase',
    require_description: 'Please fill the description',
    create_showcase_success: 'Showcase created successfully!',
    edit_showcase_pending: 'Showcase changes submitted for review!',
    edit_showcase_success: 'Showcase updated successfully!',
    create_showcase_published: 'Showcase published successfully!',
    error_saving: 'An error occurred while saving the showcase',
    create_showcase_error: 'An error occurred while creating the showcase',
    edit_showcase_error: 'An error occurred while editing the showcase',
    create_showcase_title: 'Create Showcase',
    edit_showcase_title: 'Edit Showcase',
    save_showcase_changes: 'Save Changes',
    create_showcase_desc: 'Share your other works with other teachers.',
    create_showcase_title_name: 'Title',
    create_showcase_author: 'Author(s)',
    create_showcase_description: 'Description',
    create_showcase_add_image: 'Add Image cover',
    link_to_work: 'Link to your work',
    create_showcase_image_desc: 'You can add an image to showcase your work (optional)',
    showcase_brief_description: 'Brief Description',
    change_media: 'Change Media',
    create_showcase_btn: 'Create Showcase',
    published_date: 'Date Published',
    visit_work: 'Visit the work',
    edit_showcase_published: 'Changes saved successfully!',
    create_showcase_pending: 'Your showcase has been submitted for review',
    create_showcase_author_hint: 'Search for teacher name in the system or type the name and press Enter to add',
    searching: 'Searching...',
    add: 'Add',
    no_links_provided: 'No links provided for this showcase',
    

    // All Events Page
    all_events: 'All Events',
    search_explore_events: 'Search and explore all events here',
    search_events_placeholder: 'Search by event name or keyword..',
    previous: 'Previous',
    no_events_found: 'No events found',
    no_events_found_desc: 'No events found that match your search or category',
    all_event_date: 'Date',
    all_event_time: 'Time',
    all_event_place: 'Place',
    all_event_no_brief_description: 'No brief description available',

    filter_all: 'All',
    filter_upcoming: 'Upcoming',
    filter_past: 'Past',
    filter_done: 'Done',

    // All Showcases Page
    showcases_menu: 'Showcases',
    all_showcases_title: 'All Showcases',
    search_explore_showcases: 'Search and explore all showcases here',
    search_showcases_placeholder: 'Search by title, author, or keyword..',
    no_showcases_found: 'No showcases found',
    no_showcases_found_desc: 'No showcases found that match your search or category',
    explore_showcases_desc: 'Explore showcases created by teachers to get inspiration for your own work!',
    tag_article: 'Article',
    tag_presentation: 'Presentation',

    // Admin Dashboard Sidebar
    menu: 'Menu',
    admin_menu: 'Admin Menu',
    overview: 'Overview',
    blog: 'Blogs',
    event: 'Events',
    showcase: 'Showcases',
    resource: 'Resources',
    reports: 'Reports',
    users: 'Users',
    search: 'Search...',
    status: 'Status',

    // Admin Dashboard Table
    type: 'Type',
    titleSubject: 'Title/Subject',
    submittedBy: 'Submitted by',
    date: 'Date',
    view: 'View details',
    action: 'Actions',

    // Admin Dashboard Overview
    dashboard: 'Dashboard Overview',
    pendingRequests: 'Pending Requests',
    reports_overall: 'Reports',
    totalUsers: 'Total Users',
    recentPendingRequests: 'Recent Pending Requests',
    only_admin_can_perform_this_action: 'Only admin',
    type_report: 'Report',
    type_blog: 'Blog',
    type_event: 'Event',
    type_showcase: 'Showcase',
    loading: 'Loading...',
    showing: 'Showing',
    to: 'to',
    from: 'from',
    list: 'list',
    page: 'Page',

    // Admin Blogs
    blog_title: 'Blogs Dashboard',
    no_blogs: 'No blogs found.',
    reject_blog_title: 'Reject Blog Content',
    reject_blog_reason: 'Please provide a reason :',
    reject_blog_placeholder: 'Ex. Inappropriate content / Incomplete information...',
    confirm_reject: 'Confirm',
    delete_blog_success: 'Blog deleted successfully',

    // Admin Events
    event_title: 'Events Dashboard',
    no_events: 'No events found.',
    event_actions: 'Actions',
    done: 'Mark as Done',
    event_status: 'Event Status',
    publish_state: 'Publish State',
     status_upcoming: 'Upcoming',
    status_past: 'Past',
    status_done: 'Done',
    state_pending: 'Pending',
    state_published: 'Published',
    state_rejected: 'Rejected',
    create_date: 'CreateDate',
    admin_events_confirm_approve: 'Are you sure you want to approve this event?',
    admin_events_confirm_mark_as_done: 'Are you sure you want to mark this event as "Done" ?',
    admin_events_mark_as_done_success: 'The event has been marked as Done successfully.',
    admin_events_approve_success: 'The event has been approved for publication.',
    error_updating_event_occurred: 'An error occurred while updating the event.',
    confirm: 'Confirm',
    cancel: 'Cancel',
    loading_events: 'Loading events...',
    view_event_details: 'View Event Details',
    approve: 'Approve',
    delete_event_success: 'Event deleted successfully',

    // Admin Showcases
    showcase_title: 'Showcases Dashboard',
    no_showcases: 'No showcases found.',
    loading_showcases: 'Loading showcases...',

    // Admin Reports
    report_title: 'Reports Dashboard',
    no_reports: 'No reports found.',
    loading_reports: 'Loading reports...',
    resolved: 'Resolved',
    ticket_inquiry: 'Inquiry',
    ticket_bug: 'Bug',
    ticket_comment: 'Report',
    report_category: 'Category',

    report_desc: 'Description',
    reporter: 'Reporter',
    report_date: 'Report Date',
    admin_note: 'Admin Note',
    view_source: 'View Source',

    confirm_resolved: 'Confirm Resolved',
    confirm_resolved_message: 'You are updating the status of',
    resolve_modal_placeholder: 'For example, I have removed this block from the system, I have temporarily banned the user...',
    save_report_status: 'Save Status',
    confirm_reject_message: 'You are rejecting the report',
    reject_reason: 'Reason for Rejection',
    reject_modal_placeholder: 'For example, after checking, no violation was found, insufficient information...',
    save_rejection: 'Save Rejection',
    delete_report_success: 'Report deleted successfully',
    report_pending: 'Pending',

    // Admin Users
    no_users: 'No users found.',
    id: 'Id',
    profile_pic: 'Profile Pic',
    name: 'Name',
    role: 'Role',
    joined_date: 'Joined Date',
    email: 'Email',
    school: 'School',
    province: 'Province',
    position: 'Position',
    academic_rank: 'Academic Rank',
    total_blogs: 'Total Blogs',
    total_showcases: 'Total Showcases',
    ban_user: 'Ban User',
    user: 'Users',
    account_details: 'User Details',
    post_count: 'Post',
    showcase_count: 'Works',

    confirm_ban: 'Confirm Ban',
    confirm_ban_message: 'You are banning user',
    confirm_unban: 'Confirm Unban',
    confirm_unban_message: 'You are unbanning user',
    unban_user: 'Unban User',
    are_you_sure_you_want_to_ban: 'Are you sure you want to ban this user?',
    user_banned_successfully: 'User banned successfully',
    user_unbanned_successfully: 'User unbanned successfully',
    this_user_login_disabled: 'This user will not be able to log in until they are unbanned',
    are_you_sure_you_want_to_unban: 'Are you sure you want to unban this user?',
    banned: 'Banned',

    // Confirmation Box Approve/Reject
    confirm_approve: 'Confirm Approval',
    confirm_approve_message: 'Are you sure you want to approve',
    content_will_be_published: 'This content will be published to the public',
    no_pending_requests: 'No pending requests',
    reject: 'Reject',

    // Report Modal
    report_modal_title: 'Report Issue',
    report_modal_desc: 'Report inappropriate or violating content',
    report_modal_category: 'Report Category',
    report_category_inappropriate: 'Inappropriate / Offensive Content',
    report_category_copyright_infringement: 'Copyright Infringement',
    report_category_spam_ads: 'Spam / Hidden Ads',
    report_category_false_information: 'False Information / Misleading',
    report_category_broken_links: 'Broken Links / Unavailable',
    report_category_other: 'Other',
    report_modal_description: 'Additional Details',
    report_modal_placeholder: 'Please describe the issue you found...',
    submit_report: 'Submit Report',
    report_submitted_success: 'Report submitted successfully!',
    report_submitted_error: 'An error occurred while submitting the report',
    report_success: 'Success',
    report_error: 'Error',

    // Search Page
    find_info_you_need: 'Find the information you need',
    No_results_found: 'No results found for',
    try_different_keywords: 'Try different keywords or browse all content',
    found: 'Found',
    found_for: 'items for',

    // Resource Page
    all_resources: 'All Resources',
    resources_desc: 'Search and explore all resources here',
    add_resource: 'Add Resource',
    search_resources: 'Search resources by name or keyword...',
    loading_resources: 'Loading resources...',
    no_resources_found: 'No resources found',
    no_resources_found_desc: 'No resources found matching your search or category selection',
    view_details: 'View Details',
    resource_title: 'Resource Title',
    resource_category: 'Category',
    try_different_resource_keywords: 'Try different search keywords or browse all content',

    filter_document: 'Documents',
    filter_media: 'Images & Videos',
    filter_folder: 'Folders',
    filter_link: 'Website Links',
    resource_edit_success: 'Edit successfully',
    resource_create_success: 'Create successfully',
    resource_delete_success: 'Delete successfully',

    edit_resource_title: 'Edit Resource',
    create_resource_title: 'Create Resource',
    create_resource_desc: 'Add files, documents, or videos to share with others',
    resource_type: 'Resource Type',
    resource_placeholder: 'e.g., Webinar video, Teaching materials...',
    resource_url: 'Resource URL',
    resource_description: 'Resource Description',
    resource_description_placeholder: 'Please provide a brief description of the resource...',
    create_resource_button: 'Create Resource',
    edit_resource_button: 'Save Changes',
    resource_file_size_exceeded: 'File size exceeds 10MB',
    resource_invalid_file_type: 'Invalid file type (only .jpg, .jpeg, .png, .pdf, .mp4 are supported)',

    added_on: 'Created on: ',
    no_description_provided: 'No description provided',
    open_folder: 'Open Folder',
    view_media: 'View Media',
    open_document: 'Open Document',
    open_link: 'Open Link',
    
  }
};

type Language = 'th' | 'en';

// กำหนด Type ให้ Context
interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations.th) => string; // ฟังก์ชันแปลภาษา
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  // ดึงภาษาเดิมที่เคยเลือกไว้ ถ้าไม่มีให้เริ่มที่ 'th'
  const [language, setLanguageState] = useState<Language>(
    (localStorage.getItem('app_language') as Language) || 'th'
  );

  // ฟังก์ชันเปลี่ยนภาษาและบันทึกลง Local Storage
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  // ฟังก์ชัน t (Translate) สำหรับดึงคำแปลไปแสดงผล
  const t = (key: keyof typeof translations.th) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Hook สำหรับเรียกใช้ได้จากทุกที่ในแอป
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};